"use client";

// AUTO-GENERATED by scripts/generate-social-vertical-matrix.ts
import { ComparePageWrapper } from "@/components/sections/compare/ComparePageWrapper";
import { mediaBuyersVsSmmaForCompareData } from "@/lib/compare/data/prestyj-vs-smma-for-media-buyers";

export default function PrestyjVsSmmaForMediaBuyersPage() {
  return <ComparePageWrapper data={mediaBuyersVsSmmaForCompareData} />;
}
