"use client";

// AUTO-GENERATED by scripts/generate-social-vertical-matrix.ts
import { ComparePageWrapper } from "@/components/sections/compare/ComparePageWrapper";
import { agencyOwnersVsVaPlusTemplatesForCompareData } from "@/lib/compare/data/prestyj-vs-va-plus-templates-for-agency-owners";

export default function PrestyjVsVaPlusTemplatesForAgencyOwnersPage() {
  return <ComparePageWrapper data={agencyOwnersVsVaPlusTemplatesForCompareData} />;
}
