export const siteConfig = {
  name: "Prestyj",
  legalName: "Prestyj",
  alternateNames: ["PRESTYJ", "Prestyj AI", "Prestyj Batch Video Ads"],
  title: "Prestyj | AI Lead Conversion Platform",
  description:
    "Prestyj is an AI-powered lead conversion platform with batch video ads, AI lead response, voice agents, lead reactivation, and AI sales automation for home services, real estate, and growth teams.",
  url: "https://prestyj.com",
  organizationId: "https://prestyj.com/#organization",
  websiteId: "https://prestyj.com/#website",
  logo: "https://prestyj.com/icon-512.png",
  ogImage: "https://prestyj.com/og-image.jpg",
  creator: "@prestyj_",
  email: "hello@prestyj.com",
  contactUrl: "https://prestyj.com/contact",
  foundingDate: "2026",
  sameAs: [
    "https://www.instagram.com/prestyj_/",
    "https://www.linkedin.com/company/prestyj/",
    "https://www.facebook.com/profile.php?id=61582824703610",
    "https://x.com/prestyj_",
    "https://www.wikidata.org/wiki/Q139892537",
  ],
  offerClusters: [
    "Batch video ads",
    "Paid social creative testing",
    "AI lead response",
    "AI sales agents",
    "AI voice agents",
    "AI receptionist",
    "Lead reactivation",
    "AI content department",
    "Sales automation",
    "Marketing automation",
  ],
} as const;
