export const siteConfig = {
  name: "Prestyj",
  title: "Prestyj | AI Agents for Institutional Real Estate",
  description:
    "Prestyj builds and runs AI agents for real estate investment funds, commercial brokerages, and CRE owner-operators. Deal work, fund operations, investor reporting, portfolio intelligence, and origination, delivered as reviewed work product.",
  url: "https://prestyj.com",
  organizationId: "https://prestyj.com/#organization",
  websiteId: "https://prestyj.com/#website",
  logo: "https://prestyj.com/icon-512.png",
  ogImage: "https://prestyj.com/opengraph-image",
  creator: "@prestyj_",
  email: "hello@prestyj.com",
  contactUrl: "https://prestyj.com/contact",
  foundingDate: "2026",
  sameAs: ["https://www.linkedin.com/company/prestyj/"],
  offerClusters: [
    "AI agents for real estate investment funds",
    "Institutional real estate AI",
    "Fund operations",
    "NAV and performance reporting",
    "Distribution waterfall modeling",
    "LP and investor reporting",
    "Real estate deal diligence",
    "Portfolio data reconciliation",
    "Commercial brokerage origination",
    "Listing and campaign media production",
  ],
} as const;
