export const siteConfig = {
  name: "Prestyj",
  legalName: "Prestyj",
  alternateNames: ["PRESTYJ", "Prestyj AI", "Prestyj AI Agents"],
  title: "Prestyj | Custom AI Agents, Voice Agents & Automation",
  description:
    "Prestyj builds custom AI agents, voice agents, sales and receptionist workflows, marketing/content engines, internal automation, and productized AI software for businesses.",
  url: "https://prestyj.com",
  organizationId: "https://prestyj.com/#organization",
  websiteId: "https://prestyj.com/#website",
  logo: "https://prestyj.com/icon-512.png",
  ogImage: "https://prestyj.com/og-image.jpg",
  creator: "@prestyj_",
  email: "hello@prestyj.com",
  contactUrl: "https://prestyj.com/contact",
  foundingDate: "2026",
  sameAs: [
    "https://www.instagram.com/prestyj_/",
    "https://www.linkedin.com/company/prestyj/",
    "https://www.facebook.com/profile.php?id=61582824703610",
    "https://x.com/prestyj_",
    "https://www.wikidata.org/wiki/Q139892537",
  ],
  offerClusters: [
    "Custom AI agents",
    "AI workflow automation",
    "AI voice agents",
    "AI receptionist",
    "AI sales agents",
    "AI marketing agents",
    "AI content department",
    "AI coding agents",
    "AI marketing automation",
    "Desktop AI applications",
    "Internal AI tools",
    "Batch video ads",
    "Paid social creative testing",
    "Lead response automation",
  ],
} as const;
