import type { Metadata } from "next";
import { prisma } from "@/lib/prisma";
import type { AuditResult } from "@/lib/ai-first-audit/types";
import { formatCurrencyCompact } from "@/lib/ai-first-audit/format";

interface RouteParams {
  params: Promise<{ slug: string }>;
}

export async function generateMetadata({ params }: RouteParams): Promise<Metadata> {
  const { slug } = await params;
  const audit = await prisma.aiFirstAudit.findUnique({ where: { shareSlug: slug } });

  if (!audit || audit.status !== "FINALIZED" || !audit.resultJson) {
    return {
      title: "AI-First Audit",
      description: "Personalized AI deployment audit by Prestyj.",
    };
  }

  const result = audit.resultJson as unknown as AuditResult;
  const headline = formatCurrencyCompact(result.headlineDollars);
  const title = `${result.context.firstName}'s AI-First Audit — ${headline}/yr to recover`;
  const description = `Top 3 tasks to automate first, plus a 7-day deployment plan. Generated by Prestyj.`;

  return {
    title,
    description,
    openGraph: {
      title,
      description,
      type: "article",
      url: `https://prestyj.com/ai-first-audit/r/${slug}`,
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
    },
    robots: { index: false, follow: false },
  };
}

export default function ShareLayout({ children }: { children: React.ReactNode }) {
  return children;
}
