import { createMDX } from "fumadocs-mdx/next";
import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  reactStrictMode: true,
  turbopack: {
    resolveAlias: {
      "next/dist/build/polyfills/polyfill-module": "./src/lib/noop.ts",
    },
  },
  experimental: {
    optimizePackageImports: [
      "lucide-react",
      "@radix-ui/react-accordion",
      "@radix-ui/react-dropdown-menu",
      "@radix-ui/react-dialog",
    ],
  },
  async redirects() {
    const legacyRedirects = [
      ["/ai-consulting", "/platform"],
      ["/ai-content-department", "/capabilities/listing-media"],
      ["/ai-marketing-agents", "/capabilities/listing-media"],
      ["/ai-receptionist", "/capabilities/origination"],
      ["/ai-sales-agents", "/capabilities/origination"],
      ["/ai-voice-agents", "/capabilities/origination"],
      ["/custom-ai-agents", "/platform"],
      ["/done-for-you-ai-agents", "/platform"],
      ["/done-for-you-ai-customer-support", "/platform"],
      ["/done-for-you-social-media", "/capabilities/listing-media"],
      ["/batch-video-ads", "/capabilities/listing-media"],
      ["/300-video-ads", "/capabilities/listing-media"],
      ["/ad-creative-testing-service", "/capabilities/listing-media"],
      ["/ad-creative-testing-for-dtc-brands", "/capabilities/listing-media"],
      ["/ai-performance-creative-studio", "/capabilities/listing-media"],
      ["/bulk-video-ad-pricing", "/pricing"],
      ["/video-ad-testing-pricing", "/pricing"],
      ["/youtube-media-testing-services", "/capabilities/listing-media"],
      ["/100-video-ads", "/capabilities/listing-media"],
      ["/500-video-ads", "/capabilities/listing-media"],
      ["/1000-video-ads", "/capabilities/listing-media"],
      ["/ad-fatigue-solution", "/capabilities/listing-media"],
      ["/ai-ads-vs-human-ads", "/capabilities/listing-media"],
      ["/creative-volume", "/capabilities/listing-media"],
      ["/how-many-ad-creatives-to-test", "/capabilities/listing-media"],
      ["/how-often-refresh-ad-creative", "/capabilities/listing-media"],
      ["/media-master", "/capabilities/listing-media"],
      ["/meta-ad-creative-testing", "/capabilities/listing-media"],
      ["/run-my-first-facebook-ads", "/capabilities/listing-media"],
      ["/scale-facebook-ads-with-more-creative", "/capabilities/listing-media"],
      ["/tiktok-ad-creative-testing", "/capabilities/listing-media"],
      ["/why-facebook-ads-stop-working", "/capabilities/listing-media"],
      ["/ai-first-audit", "/book-demo"],
      ["/founding-cohort", "/pilot"],
      ["/affiliate", "/contact"],
      ["/checkout", "/pricing"],
      ["/ad-to-appointment-atlas", "/research"],
      ["/data", "/research"],
      ["/statistics", "/research"],
      ["/batch-video-ad-roi-calculator", "/research"],
      ["/cost-per-tested-ad-angle-calculator", "/research"],
      ["/home-services-roi-calculator", "/research"],
      ["/ai-calculator-results", "/research"],
      ["/team-commission-calculator", "/commercial-real-estate-commission-calculator"],
      ["/commission-split-calculator", "/commercial-real-estate-commission-calculator"],
      ["/real-estate-deal-analysis-calculator", "/commercial-real-estate-commission-calculator"],
      ["/real-estate-roi-calculator", "/commercial-real-estate-commission-calculator"],
      ["/ai-call-handling-calculator", "/commercial-real-estate-commission-calculator"],
      ["/lead-response-cost-calculator", "/commercial-real-estate-commission-calculator"],
      ["/intake", "/book-demo"],
      ["/onboarding", "/book-demo"],
      ["/start", "/book-demo"],
      ["/google-free-ads-for-contractors", "/capabilities/listing-media"],
      ["/google-free-ads-for-home-services", "/capabilities/listing-media"],
      ["/google-free-ads-program", "/capabilities/listing-media"],
      ["/free-ads-case-study", "/results"],
      ["/free-ads-for-agencies", "/capabilities/listing-media"],
      ["/free-ads-for-auto-dealers", "/capabilities/listing-media"],
      ["/free-ads-for-business-coaches", "/capabilities/listing-media"],
      ["/free-ads-for-creators", "/capabilities/listing-media"],
      ["/free-ads-for-dentists", "/capabilities/listing-media"],
      ["/free-ads-for-ecommerce", "/capabilities/listing-media"],
      ["/free-ads-for-financial-advisors", "/capabilities/listing-media"],
      ["/free-ads-for-fitness-coaches", "/capabilities/listing-media"],
      ["/free-ads-for-home-services", "/capabilities/listing-media"],
      ["/free-ads-for-hvac", "/capabilities/listing-media"],
      ["/free-ads-for-insurance-agents", "/capabilities/listing-media"],
      ["/free-ads-for-lawyers", "/capabilities/listing-media"],
      ["/free-ads-for-med-spas", "/capabilities/listing-media"],
      ["/free-ads-for-mortgage-brokers", "/capabilities/listing-media"],
      ["/free-ads-for-personal-brands", "/capabilities/listing-media"],
      ["/free-ads-for-plumbers", "/capabilities/listing-media"],
      ["/free-ads-for-real-estate-agents", "/capabilities/listing-media"],
      ["/free-ads-for-restaurants", "/capabilities/listing-media"],
      ["/free-ads-for-roofers", "/capabilities/listing-media"],
      ["/free-ads-for-saas", "/capabilities/listing-media"],
      ["/free-ads-for-solar-companies", "/capabilities/listing-media"],
      ["/free-ads-for-wellness-coaches", "/capabilities/listing-media"],
    ] as const;

    return [
      ...legacyRedirects.map(([source, destination]) => ({
        source,
        destination,
        permanent: true,
      })),
      { source: "/compare/:path*", destination: "/platform", permanent: true },
      { source: "/alternatives/:path*", destination: "/platform", permanent: true },
      { source: "/best-for/:path*", destination: "/for/investment-funds", permanent: true },
      { source: "/solutions/:path*", destination: "/capabilities/origination", permanent: true },
      { source: "/locations/:path*", destination: "/", permanent: true },
      { source: "/free-ads/:path*", destination: "/capabilities/listing-media", permanent: true },
      { source: "/lead-magnet/:path*", destination: "/research", permanent: true },
      { source: "/ai-first-audit/:path*", destination: "/book-demo", permanent: true },
      {
        source: "/ai-content-department/:path*",
        destination: "/capabilities/listing-media",
        permanent: true,
      },
      { source: "/affiliate/:path*", destination: "/contact", permanent: true },
      { source: "/checkout/:path*", destination: "/pricing", permanent: true },
      { source: "/founding-cohort/:path*", destination: "/pilot", permanent: true },
      { source: "/intake/:path*", destination: "/book-demo", permanent: true },
      { source: "/onboarding/:path*", destination: "/book-demo", permanent: true },
      { source: "/start/:path*", destination: "/book-demo", permanent: true },
      { source: "/r/:path*", destination: "/", permanent: true },
      {
        source: "/team-commission-calculator/:path*",
        destination: "/commercial-real-estate-commission-calculator",
        permanent: true,
      },
      {
        source: "/embed/calculator/:path*",
        destination: "/commercial-real-estate-commission-calculator",
        permanent: true,
      },
      { source: "/embed/stat/:path*", destination: "/research", permanent: true },
      { source: "/blog/author/:path*", destination: "/about", permanent: true },
      { source: "/blog/category/:path*", destination: "/blog", permanent: true },
      { source: "/blog/page/:path*", destination: "/blog", permanent: true },
      { source: "/stat/:path*", destination: "/research", permanent: true },
      { source: "/statistics/:path*", destination: "/research", permanent: true },
      { source: "/data/:path*", destination: "/research", permanent: true },
      { source: "/feed/stats.xml", destination: "/feed/blog.xml", permanent: true },
      { source: "/feed/statistics.xml", destination: "/feed/blog.xml", permanent: true },
      { source: "/lead-magnets/:path*", destination: "/research", permanent: true },
    ];
  },
};

const withMDX = createMDX();

export default withMDX(nextConfig);
