"use client";

// AUTO-GENERATED by scripts/generate-batch-video-ad-matrix.ts
import { ComparePageWrapper } from "@/components/sections/compare/ComparePageWrapper";
import { realEstateTeamsVsAiAvatarToolVideoCompareData } from "@/lib/compare/data/prestyj-vs-ai-avatar-tool-video-for-real-estate-teams";

export default function PrestyJVsAiAvatarToolForRealEstateTeamsPage() {
  return <ComparePageWrapper data={realEstateTeamsVsAiAvatarToolVideoCompareData} />;
}
