"use client";

// AUTO-GENERATED by scripts/generate-batch-video-ad-matrix.ts
import { ComparePageWrapper } from "@/components/sections/compare/ComparePageWrapper";
import { mortgageBrokersVsAgencyVideoCompareData } from "@/lib/compare/data/prestyj-vs-agency-video-for-mortgage-brokers";

export default function PrestyJVsAgencyForMortgageBrokersPage() {
  return <ComparePageWrapper data={mortgageBrokersVsAgencyVideoCompareData} />;
}
