"use client";

// AUTO-GENERATED by scripts/generate-batch-video-ad-matrix.ts
import { ComparePageWrapper } from "@/components/sections/compare/ComparePageWrapper";
import { roofingContractorsVsInHouseVideoCompareData } from "@/lib/compare/data/prestyj-vs-in-house-video-for-roofing-contractors";

export default function PrestyJVsInHouseForRoofingContractorsPage() {
  return <ComparePageWrapper data={roofingContractorsVsInHouseVideoCompareData} />;
}
