import type { BestForPageContent } from "./types";

// AUTO-GENERATED by scripts/generate-batch-video-ad-matrix.ts
// Vertical: Plumbing Contractors · Angle: batch video ads
export const batchVideoAdsForPlumbingContractors: BestForPageContent = {
  slug: "batch-video-ads-for-plumbing-contractors",
  niche: {
    name: "Batch Video Ads for Plumbing Contractors",
    shortName: "Plumbing",
    description:
      "residential and commercial plumbing contractors running $1M-$15M/year with 3-30 trucks using batch video ad creative testing to compress 6 weeks of production into 24 hours and finally feed the algorithm enough creative volume to exit learning.",
  },
  meta: {
    title: "Batch Video Ads for Plumbing Contractors: 500 Ads in 24 Hours (From $1,497) | PRESTYJ",
    description:
      "Plumbing Contractors ship 8 ads a quarter. Batch ships 300-1,000 in 24 hours from one 20-minute recording — flat fee, scripts written for you, your real face. From $1,497.",
    keywords: [
      "batch video ads for plumbing-contractors",
      "video ads for plumbing-contractors",
      "plumbing facebook ads creative",
      "plumbing video ad production",
      "scaled creative testing for plumbing-contractors",
      "plumbing ad fatigue solution",
      "done for you video ads plumbing-contractors",
      "creative volume for plumbing-contractors",
    ],
  },
  hero: {
    badge: "Batch Video Ads for Plumbing",
    headline: "Plumbing Contractors Need 50 Fresh Ads a Month.",
    headlineAccent: "Most Ship 4. Here's How Batch Solves It.",
    subheadline:
      "Residential and commercial plumbing contractors running $1M-$15M/year with 3-30 trucks live or die on creative volume. Meta and TikTok exit the learning phase at roughly 50 fresh creatives per ad set — and most Plumbing ship 4 a quarter. Prestyj turns one 20-minute recording into 300-1,000 scripted vertical video ads, delivered in 24 hours, scripted for Plumbing pain points specifically. Flat fee. Your real face. No retainer.",
  },
  whyBestFor: [
    {
      icon: "Zap",
      title: "Sewer-line jobs and water-heater jobs are different audiences — and your one ad treats them as one",
      description:
        "This is the #1 silent killer for Plumbing on paid social. The platforms reward creative diversity and punish repetition. When you ship 4 ads, you live in the learning phase forever — your CPL never compresses, the algorithm never finds your buyer cluster, and you blame the channel when the real bottleneck is creative volume. Batch fixes the volume problem in one delivery.",
    },
    {
      icon: "Target",
      title: "Emergency leak ads vs preventive repipe ads need different creative — you ship one generic 'we do plumbing' video",
      description:
        "Different audiences need different hooks. Generic creative averages everything down. Plumbing who run 5-10 angle-specific tracks (instead of one 'general' track) consistently see $18-$44 per booked appointment versus the $95-$210 per aggregator lead (sold to 3 competitors) they were getting before. Batch is engineered around angle-testing — every batch ships with multiple distinct hook tracks ready to A/B at the ad-set level.",
    },
    {
      icon: "DollarSign",
      title: "Your warranty pitch and your financing pitch never appear in the same ad rotation because you only have 2 ads",
      description:
        "When the unit economics are this big — $220 service call → $4,500-$28,000 repipe / sewer / water-heater install — you cannot afford to be creative-starved. A single additional booked deal pays for the entire batch many times over. The math for Plumbing is some of the most favorable in the entire batch-creative space.",
    },
    {
      icon: "Clock",
      title: "Your retainer agency ships ads in 14 days. Batch ships in 24 hours.",
      description:
        "The hidden cost is mismatched-intent traffic — generic plumbing ads pull tire-kickers while specific 'water-heater replacement' or 'slab leak' ads pull buyers. The only way to win is to ship event-specific or audience-specific creative inside the window when it matters. Batch turnaround is 24 hours from footage delivery — meaning you can record on a Monday and have hundreds of new ads live by Tuesday afternoon.",
    },
    {
      icon: "Sparkles",
      title: "Scripts are vertical-researched, not generic 'video ads'",
      description:
        "Every batch begins with a vertical research pass. We pull the highest-converting hook patterns from current-quarter ad libraries in your space, mix them with your specific offer and pricing, and write 300-1,000 distinct scripts designed to test which angle wins for your business — not someone else's. This is the difference between batch creative that works and batch creative that's just volume.",
    },
  ],
  painPoints: [
    {
      problem: "You spent $5K-$50K on Facebook ads, got disappointing CPL, and concluded 'paid social doesn't work for Plumbing'",
      solution:
        "It's almost never the channel — it's almost always the creative volume. Meta needs roughly 30-50 fresh creatives per ad set to exit learning. If you tested 3 ads, you never left learning. After a single batch delivery, Plumbing consistently see CPL drop 40-70% in the first 30 days because the algorithm finally has enough fuel to optimize.",
    },
    {
      problem: "Your in-house team / freelancer / agency ships 2-8 video ads per month — far below what the platforms need",
      solution:
        "This is the bottleneck the entire industry is hitting. Production capacity has not scaled with platform demand. A Prestyj batch ships in one day what your current pipeline ships in two quarters — without you firing anyone or restructuring your team.",
    },
    {
      problem: "You don't have time to write scripts, pick angles, or manage a video production process",
      solution:
        "You don't have to. Send us a creative brief (we have a 5-question form) and 15-20 minutes of selfie footage. We write every script, mix every variation, and deliver. Your only job is recording the footage and approving the final batch.",
    },
    {
      problem: "Your creative looks identical to every other plumbing in your market",
      solution:
        "Generic creative is what happens when production is scarce. When production is abundant, you can finally afford to ship specific creative — specific to your market, specific to your offer, specific to a sub-audience. Batch makes specific cheap.",
    },
    {
      problem: "You worry batch creative will dilute your brand or look low-quality",
      solution:
        "Every batch is reviewed before delivery. You record in good light with reasonable audio (we send a one-page setup guide), and we handle the rest. The ads look like exactly what they are: a real plumbing talking about real pain points — which is what converts on Meta and TikTok in 2026.",
    },
  ],
  comparison: {
    headers: ["Feature", "Prestyj Batch Video Ads", "Fiverr Video Editors / Status Quo"],
    rows: [
      {
        feature: "Ad creatives shipped per delivery",
        prestyj: "300-1,000",
        others: "1-8",
      },
      {
        feature: "Turnaround time",
        prestyj: "24 hours from footage",
        others: "1-4 weeks",
      },
      {
        feature: "Pricing model",
        prestyj: "Flat one-time fee from $1,497",
        others: "$25-$500per gig",
      },
      {
        feature: "Scripts written for you (vertical-specific)",
        prestyj: "Yes — researched per batch",
        others: "No — you write briefs or scripts",
      },
      {
        feature: "Cost per ad (at 500-ad tier)",
        prestyj: "≈ $5",
        others: "$25-$500 each",
      },
      {
        feature: "Uses your real face / your actual company",
        prestyj: "Always",
        others: "Sometimes",
      },
      {
        feature: "Built for ad fatigue / creative refresh cycles",
        prestyj: "Designed for 50+ ad/set rotation",
        others: "Not architected for refresh cadence",
      },
    ],
  },
  faq: [
    {
      question: "How is this different from generic 'video ads for plumbing-contractors'?",
      answer:
        "Generic 'video ads for plumbing-contractors' usually means a retainer agency producing 4-8 videos a month at $4K-$15K/month. Batch is a fundamentally different unit: 300-1,000 scripted variations from one recording, delivered in 24 hours, flat fee. It exists because the platforms changed — Meta and TikTok now require creative volume to exit the learning phase, and the old monthly-retainer model cannot supply that volume.",
    },
    {
      question: "What does cost per tested ad angle actually look like for Plumbing?",
      answer:
        "At the 500-ad tier ($2,497), if we ship 5 distinct hook angles you get roughly 100 variations per angle — meaning your effective cost per fully tested angle is around $500. Compare that to a retainer agency where one new angle costs you a full month of fees ($4K-$15K) and ships 1-2 videos. The cost-per-tested-angle math is what makes batch viable for Plumbing who need to test many positions before committing budget.",
    },
    {
      question: "Will the ads actually look like 'me' or like generic UGC?",
      answer:
        "You record yourself. We never use AI avatars, hired actors, or stock voiceover. Every ad in the batch features your real face, your real voice, and the real footage you sent. That's the entire point — for plumbing, authenticity is the conversion engine and batch lets you scale authenticity instead of replacing it with synthetic content.",
    },
    {
      question: "How fast can I be running ads after we kick off?",
      answer:
        "Standard timeline: kickoff Monday, you record Tuesday, we deliver Wednesday, you upload to your ad account Wednesday afternoon and run by Thursday. Total: 4 days from signed contract to live ads. Compare to a retainer agency where 4 days is a single revision cycle.",
    },
    {
      question: "What's the catch on the $1,497 pricing?",
      answer:
        "There isn't one — it's a flat fee for 300 ads / 3 angles. We make money because the production system is engineered for batch output, not because we're hiding costs. Most Plumbing start at the $2,497 tier (500 ads / 5 angles) because the cost-per-angle math is significantly better there.",
    },
  ],
  cta: {
    headline: "Plumbing Contractors: 500 Real Video Ads in 24 Hours.",
    subheadline:
      "One 20-minute recording. Plumbing-specific scripts. 300-1,000 ready-to-test ads. Flat fee from $1,497. No retainer, no subscription.",
    buttonText: "Pick My Batch",
    buttonHref: "/batch-video-ads#pricing",
    footnote: "One-time pricing from $1,497 · 24-hour delivery · No retainer",
  },
};
