import type { BestForPageContent } from "./types";

// AUTO-GENERATED by scripts/generate-batch-video-ad-organic-matrix.ts
// Vertical: Solar Companies · Angle: batch video ads
export const batchVideoAdsForSolarCompanies: BestForPageContent = {
  slug: "batch-video-ads-for-solar-companies",
  niche: {
    name: "Batch Video Ads for Solar Companies",
    shortName: "Solar",
    description: "residential solar companies and dealers selling consultations in competitive local markets that need enough vertical ad variations to test paid social angles without waiting weeks for production.",
  },
  meta: {
    title: "Batch Video Ads for Solar Companies | 100-1,000 Ads",
    description: "Batch video ads for solar: turn one recording into 100, 300, 500, or 1,000 vertical ad variations built around homeowners are skeptical because bad solar ads overpromised savings for years.",
    keywords: [
      "batch video ads for solar",
      "video ads for solar-companies",
      "solar video ad production",
      "solar facebook ads creative",
      "solar ad creative volume",
      "100 video ads for solar-companies",
    ],
  },
  hero: {
    badge: "Batch Video Ads for Solar",
    headline: "Solar Companies Need More Than One Generic Video Ad.",
    headlineAccent: "Batch gives you the creative volume to find what buyers respond to.",
    subheadline: "Prestyj turns one founder or operator recording into 100-1,000 scripted vertical ad variations for solar. Test pain points, seasonal triggers like summer utility bills, and high-intent offers without hiring another editor, agency, or creator.",
  },
  whyBestFor: [
    {
      icon: "Target",
      title: "Homeowners are skeptical because bad solar ads overpromised savings for years.",
      description: "Solar campaigns underperform when every buyer sees the same generic message. Batch creative splits the market into specific angles — The bill shock this summer hook, The battery during outage hook, and other hooks that let the account learn which problem actually creates demand.",
    },
    {
      icon: "DollarSign",
      title: "The economics support testing: $18,000-$55,000 solar installation",
      description: "Solar lead costs swing hard with rates, incentives, and trust issues. Test utility-bill, incentive, battery, ownership, and skepticism angles without repeating stale savings claims. When one booked opportunity can justify the whole production sprint, starving the account with three ads is the expensive option.",
    },
    {
      icon: "Clock",
      title: "Summer utility bills windows move faster than traditional production.",
      description: "The best solar angles are often tied to timing: summer utility bills, tax credit deadlines, storm outage season, rate hike announcements. Batch production gives your team ready-to-test creative while the trigger is still active instead of after the opportunity has passed.",
    },
    {
      icon: "Shield",
      title: "Compliance-aware scripts keep volume from becoming reckless.",
      description: "Avoid guaranteed savings, tax credit eligibility promises, or utility-specific claims without verification.",
    },
    {
      icon: "Sparkles",
      title: "Your real operator beats shared solar leads and door-to-door appointment setters.",
      description: "The status quo for solar is shared solar leads and door-to-door appointment setters. Prestyj uses your real face, your real offer, and a structured script matrix so the account gets authenticity and volume at the same time.",
    },
  ],
  painPoints: [
    {
      problem: "Homeowners are skeptical because bad solar ads overpromised savings for years.",
      solution: "Build a full lane of ads around that problem instead of mentioning it once. Prestyj turns it into hooks, proof points, objections, and CTAs so your media buyer can see whether the market cares.",
    },
    {
      problem: "Battery, bill savings, ownership, and incentive messages need separate tests.",
      solution: "Use batch production to test separate ad families for each buyer motivation. Solar can compare urgency, trust, cost, timing, and status quo angles without another shoot.",
    },
    {
      problem: "Local utility and rate context changes faster than old creative calendars.",
      solution: "Give that high-value category its own creative inventory. A 300, 500, or 1,000 ad batch lets your team isolate which offer deserves more spend.",
    },
    {
      problem: "You are relying on shared solar leads and door-to-door appointment setters instead of owned creative learning.",
      solution: "Batch creative gives solar a reusable library that can be launched, paused, refreshed, and expanded without renting every lead from the same crowded channels.",
    },
    {
      problem: "You do not have time to write solar ad scripts from scratch.",
      solution: "Prestyj writes the scripts, maps the angles, edits the recording, and delivers finished vertical files. Your team records once and your media buyer gets the creative inputs.",
    },
  ],
  comparison: {
    headers: ["Factor", "Prestyj Batch Video Ads", "Shared solar leads and door To Door appointment setters"],
    rows: [
      {
        feature: "Creative output",
        prestyj: "100, 300, 500, or 1,000 finished ads",
        others: "A handful of generic ads or rented leads",
      },
      {
        feature: "Angle coverage",
        prestyj: "The bill shock this summer hook, The battery during outage hook, The no more door-knocker pitch hook, The tax credit deadline education hook",
        others: "Usually one broad message",
      },
      {
        feature: "Production model",
        prestyj: "One recording session plus a scripted variation matrix",
        others: "New brief, vendor, or campaign for every idea",
      },
      {
        feature: "Economics",
        prestyj: "Test utility-bill, incentive, battery, ownership, and skepticism angles without repeating stale savings claims.",
        others: "Solar lead costs swing hard with rates, incentives, and trust issues.",
      },
      {
        feature: "Primary CTA",
        prestyj: "Send traffic to the winning offer and refresh before fatigue",
        others: "Wait for the next production cycle",
      },
    ],
  },
  faq: [
    {
      question: "How do batch video ads work for solar?",
      answer: "Prestyj writes a solar-specific script matrix, you record the scripts once, and we edit that footage into finished vertical ad variations for Meta, TikTok, YouTube Shorts, and similar placements.",
    },
    {
      question: "What angles should solar test first?",
      answer: "Start with The bill shock this summer hook, The battery during outage hook, The no more door-knocker pitch hook, The tax credit deadline education hook. Those angles map to real solar buying triggers instead of generic brand awareness.",
    },
    {
      question: "Is this a replacement for shared solar leads and door-to-door appointment setters?",
      answer: "It replaces the creative production bottleneck, not every marketing function. Your team or agency still manages media buying; Prestyj supplies the high-volume ad creative library.",
    },
    {
      question: "What compliance guardrails matter for solar ads?",
      answer: "Avoid guaranteed savings, tax credit eligibility promises, or utility-specific claims without verification.",
    },
    {
      question: "Which batch size should solar choose?",
      answer: "Choose 100 ads for a focused first test, 300 for three problem lanes, 500 for the recommended matrix, and 1,000 if you need to test many solar triggers or refresh a larger account.",
    },
  ],
  cta: {
    headline: "Solar Companies: Turn One Recording Into a Paid-Social Test Library.",
    subheadline: "Get scripts and finished video ads built around solar economics, timing triggers, compliance constraints, and buyer objections.",
    buttonText: "See Batch Pricing",
    buttonHref: "/batch-video-ads#pricing",
    footnote: "One-time packs from $497 · Cost-per-angle calculator available",
  },
};
