import type { BestForPageContent } from "./types";

// AUTO-GENERATED by scripts/generate-batch-video-ad-matrix.ts
// Vertical: Service Business Owners · Angle: batch video ads
export const batchVideoAdsForServiceBusinessOwners: BestForPageContent = {
  slug: "batch-video-ads-for-service-business-owners",
  niche: {
    name: "Batch Video Ads for Service Business Owners",
    shortName: "Service Business Owners",
    description:
      "service business owners running $500K-$10M/year operations across home services, professional services, and local trades using batch video ad creative testing to compress 6 weeks of production into 24 hours and finally feed the algorithm enough creative volume to exit learning.",
  },
  meta: {
    title: "Batch Video Ads for Service Business Owners: 500 Ads in 24 Hours (From $1,497) | PRESTYJ",
    description:
      "Service Business Owners ship 8 ads a quarter. Batch ships 300-1,000 in 24 hours from one 20-minute recording — flat fee, scripts written for you, your real face. From $1,497.",
    keywords: [
      "batch video ads for service-business-owners",
      "video ads for service-business-owners",
      "service business owners facebook ads creative",
      "service business owners video ad production",
      "scaled creative testing for service-business-owners",
      "service business owners ad fatigue solution",
      "done for you video ads service-business-owners",
      "creative volume for service-business-owners",
    ],
  },
  hero: {
    badge: "Batch Video Ads for Service Business Owners",
    headline: "Service Business Owners Need 50 Fresh Ads a Month.",
    headlineAccent: "Most Ship 4. Here's How Batch Solves It.",
    subheadline:
      "Service business owners running $500K-$10M/year operations across home services, professional services, and local trades live or die on creative volume. Meta and TikTok exit the learning phase at roughly 50 fresh creatives per ad set — and most Service Business Owners ship 4 a quarter. Prestyj turns one 20-minute recording into 300-1,000 scripted vertical video ads, delivered in 24 hours, scripted for Service Business Owners pain points specifically. Flat fee. Your real face. No retainer.",
  },
  whyBestFor: [
    {
      icon: "Zap",
      title: "Lead aggregator costs are up 60% in 24 months and you still don't own the customer",
      description:
        "This is the #1 silent killer for Service Business Owners on paid social. The platforms reward creative diversity and punish repetition. When you ship 4 ads, you live in the learning phase forever — your CPL never compresses, the algorithm never finds your buyer cluster, and you blame the channel when the real bottleneck is creative volume. Batch fixes the volume problem in one delivery.",
    },
    {
      icon: "Target",
      title: "You tried Facebook ads, spent $3K, got 4 leads, and your agency blamed 'the algorithm'",
      description:
        "Different audiences need different hooks. Generic creative averages everything down. Service Business Owners who run 5-10 angle-specific tracks (instead of one 'general' track) consistently see $18-$45 per booked appointment versus the $80-$220 per appointment via Yelp/Angi/Thumbtack they were getting before. Batch is engineered around angle-testing — every batch ships with multiple distinct hook tracks ready to A/B at the ad-set level.",
    },
    {
      icon: "DollarSign",
      title: "Every truck on the road is a billboard you already paid for — and zero of it is in any ad",
      description:
        "When the unit economics are this big — $800-$20,000 per closed job depending on trade — you cannot afford to be creative-starved. A single additional booked deal pays for the entire batch many times over. The math for Service Business Owners is some of the most favorable in the entire batch-creative space.",
    },
    {
      icon: "Clock",
      title: "Your retainer agency ships ads in 14 days. Batch ships in 24 hours.",
      description:
        "The hidden cost of relying on aggregators is permanent pricing pressure — they sell the same lead to 3 competitors and your close rate collapses. The only way to win is to ship event-specific or audience-specific creative inside the window when it matters. Batch turnaround is 24 hours from footage delivery — meaning you can record on a Monday and have hundreds of new ads live by Tuesday afternoon.",
    },
    {
      icon: "Sparkles",
      title: "Scripts are vertical-researched, not generic 'video ads'",
      description:
        "Every batch begins with a vertical research pass. We pull the highest-converting hook patterns from current-quarter ad libraries in your space, mix them with your specific offer and pricing, and write 300-1,000 distinct scripts designed to test which angle wins for your business — not someone else's. This is the difference between batch creative that works and batch creative that's just volume.",
    },
  ],
  painPoints: [
    {
      problem: "You spent $5K-$50K on Facebook ads, got disappointing CPL, and concluded 'paid social doesn't work for Service Business Owners'",
      solution:
        "It's almost never the channel — it's almost always the creative volume. Meta needs roughly 30-50 fresh creatives per ad set to exit learning. If you tested 3 ads, you never left learning. After a single batch delivery, Service Business Owners consistently see CPL drop 40-70% in the first 30 days because the algorithm finally has enough fuel to optimize.",
    },
    {
      problem: "Your in-house team / freelancer / agency ships 2-8 video ads per month — far below what the platforms need",
      solution:
        "This is the bottleneck the entire industry is hitting. Production capacity has not scaled with platform demand. A Prestyj batch ships in one day what your current pipeline ships in two quarters — without you firing anyone or restructuring your team.",
    },
    {
      problem: "You don't have time to write scripts, pick angles, or manage a video production process",
      solution:
        "You don't have to. Send us a creative brief (we have a 5-question form) and 15-20 minutes of selfie footage. We write every script, mix every variation, and deliver. Your only job is recording the footage and approving the final batch.",
    },
    {
      problem: "Your creative looks identical to every other service business owners in your market",
      solution:
        "Generic creative is what happens when production is scarce. When production is abundant, you can finally afford to ship specific creative — specific to your market, specific to your offer, specific to a sub-audience. Batch makes specific cheap.",
    },
    {
      problem: "You worry batch creative will dilute your brand or look low-quality",
      solution:
        "Every batch is reviewed before delivery. You record in good light with reasonable audio (we send a one-page setup guide), and we handle the rest. The ads look like exactly what they are: a real service business owners talking about real pain points — which is what converts on Meta and TikTok in 2026.",
    },
  ],
  comparison: {
    headers: ["Feature", "Prestyj Batch Video Ads", "Marketing Agencies / Status Quo"],
    rows: [
      {
        feature: "Ad creatives shipped per delivery",
        prestyj: "300-1,000",
        others: "1-8",
      },
      {
        feature: "Turnaround time",
        prestyj: "24 hours from footage",
        others: "1-4 weeks",
      },
      {
        feature: "Pricing model",
        prestyj: "Flat one-time fee from $1,497",
        others: "$3,500-$8,000/month retainer",
      },
      {
        feature: "Scripts written for you (vertical-specific)",
        prestyj: "Yes — researched per batch",
        others: "No — you write briefs or scripts",
      },
      {
        feature: "Cost per ad (at 500-ad tier)",
        prestyj: "≈ $5",
        others: "$200-$2,000 each fully loaded",
      },
      {
        feature: "Uses your real face / your actual brand",
        prestyj: "Always",
        others: "Sometimes",
      },
      {
        feature: "Built for ad fatigue / creative refresh cycles",
        prestyj: "Designed for 50+ ad/set rotation",
        others: "Not architected for refresh cadence",
      },
    ],
  },
  faq: [
    {
      question: "How is this different from generic 'video ads for service-business-owners'?",
      answer:
        "Generic 'video ads for service-business-owners' usually means a retainer agency producing 4-8 videos a month at $4K-$15K/month. Batch is a fundamentally different unit: 300-1,000 scripted variations from one recording, delivered in 24 hours, flat fee. It exists because the platforms changed — Meta and TikTok now require creative volume to exit the learning phase, and the old monthly-retainer model cannot supply that volume.",
    },
    {
      question: "What does cost per tested ad angle actually look like for Service Business Owners?",
      answer:
        "At the 500-ad tier ($2,497), if we ship 5 distinct hook angles you get roughly 100 variations per angle — meaning your effective cost per fully tested angle is around $500. Compare that to a retainer agency where one new angle costs you a full month of fees ($4K-$15K) and ships 1-2 videos. The cost-per-tested-angle math is what makes batch viable for Service Business Owners who need to test many positions before committing budget.",
    },
    {
      question: "Will the ads actually look like 'me' or like generic UGC?",
      answer:
        "You record yourself. We never use AI avatars, hired actors, or stock voiceover. Every ad in the batch features your real face, your real voice, and the real footage you sent. That's the entire point — for service business owners, authenticity is the conversion engine and batch lets you scale authenticity instead of replacing it with synthetic content.",
    },
    {
      question: "How fast can I be running ads after we kick off?",
      answer:
        "Standard timeline: kickoff Monday, you record Tuesday, we deliver Wednesday, you upload to your ad account Wednesday afternoon and run by Thursday. Total: 4 days from signed contract to live ads. Compare to a retainer agency where 4 days is a single revision cycle.",
    },
    {
      question: "What's the catch on the $1,497 pricing?",
      answer:
        "There isn't one — it's a flat fee for 300 ads / 3 angles. We make money because the production system is engineered for batch output, not because we're hiding costs. Most Service Business Owners start at the $2,497 tier (500 ads / 5 angles) because the cost-per-angle math is significantly better there.",
    },
  ],
  cta: {
    headline: "Service Business Owners: 500 Real Video Ads in 24 Hours.",
    subheadline:
      "One 20-minute recording. Service Business Owners-specific scripts. 300-1,000 ready-to-test ads. Flat fee from $1,497. No retainer, no subscription.",
    buttonText: "Book a Demo",
    buttonHref: "/book-demo",
    footnote: "One-time pricing from $1,497 · 24-hour delivery · No retainer",
  },
};
