import type { BestForPageContent } from "./types";

// AUTO-GENERATED by scripts/generate-batch-video-ad-matrix.ts
// Vertical: Coaches · Angle: cost per tested ad angle (pricing math)
export const costPerTestedAdAngleForCoaches: BestForPageContent = {
  slug: "cost-per-tested-ad-angle-for-coaches",
  niche: {
    name: "Cost Per Tested Ad Angle for Coaches",
    shortName: "Coaches",
    description:
      "Pricing math for high-ticket coaches, course creators, and group-program operators who need to know the true unit cost of testing a new ad angle — not the headline price of a video, but the fully-loaded cost to run, learn, and decide on one positioning hypothesis.",
  },
  meta: {
    title: "Cost Per Tested Ad Angle for Coaches (2026 Math) | PRESTYJ",
    description:
      "What does it actually cost to test one ad angle for Coaches? Agency: $4K-$15K. Freelancer: $2K-$8K. Batch: ≈$500. Full pricing math, fatigue tax, and hidden costs broken down.",
    keywords: [
      "cost per ad angle coaches",
      "cost per tested creative coaches",
      "coaches ad creative pricing",
      "video ad pricing for coaches",
      "hidden costs of coaches video ads",
      "coaches creative testing cost",
      "ad angle testing pricing coaches",
      "cost per fresh creative coaches",
    ],
  },
  hero: {
    badge: "Pricing Math for Coaches",
    headline: "What Does It Actually Cost to Test One Ad Angle for Coaches?",
    headlineAccent: "Headline Price ≠ Tested Cost.",
    subheadline:
      "Most coaches compare ad creative on per-video price. That's the wrong unit. The unit that matters is cost per tested angle — the fully-loaded cost to ship enough variations of one hook to actually learn whether it converts. Agency math, freelancer math, in-house math, and batch math give wildly different answers. Here is the breakdown.",
  },
  whyBestFor: [
    {
      icon: "DollarSign",
      title: "Per-video pricing hides the real cost",
      description:
        "A $300 Fiverr video sounds cheap. But to actually test that angle you need 30-50 variations of it (different hooks, different B-roll, different CTA). That's $9,000-$15,000 of Fiverr gigs to learn one angle. Batch math: ≈$500 per fully tested angle at the 500-ad / 5-angle tier. The per-video number is a distraction.",
    },
    {
      icon: "BarChart3",
      title: "Algorithm exit cost is the real benchmark",
      description:
        "Meta needs roughly 50 fresh creatives per ad set to leave the learning phase. If your test does not include enough variations to exit learning, your CPL data is noise — you spent the money and learned nothing. Cost per tested angle has to include 'enough variations to exit learning' or it is not a real test.",
    },
    {
      icon: "Percent",
      title: "Fatigue tax compounds every 7-14 days",
      description:
        "Even a winning angle dies inside 14-21 days as frequency builds. Cost per tested angle has to include the refresh — you do not test once, you test, ship, refresh, repeat. The hidden cost of running coach ads is creative fatigue tax — your CPL doubles every 3 weeks until you ship fresh creative.",
    },
    {
      icon: "Clock",
      title: "Time-to-learning is part of the cost",
      description:
        "An agency angle takes 14-30 days to ship 1-2 videos. A batch angle ships in 24 hours with 100 variations. The opportunity cost of waiting 30 days to start a test is invisible on an invoice but very real in your P&L — especially for coaches where $2,000-$25,000 per client.",
    },
    {
      icon: "Filter",
      title: "Most 'video ad pricing' calculators ignore script research",
      description:
        "If you give a freelancer a script, that's one cost. If you ask them to research your vertical and write the script, you've doubled the price and added 2 weeks. Batch pricing includes vertical-researched scripts written for Coaches pain points specifically. That's bundled, not extra.",
    },
  ],
  painPoints: [
    {
      problem: "You compared a $300 freelancer video to a $1,497 batch and the freelancer 'won' — but you tested 1 ad and it failed",
      solution:
        "You did not test an angle. You tested an ad. An angle is a hook + body + CTA pattern with enough variations to exit Meta's learning phase. One ad cannot do that. The freelancer comparison is apples-to-oranges. Per-tested-angle math reveals the freelancer route at $9K-$15K versus batch at ≈$500.",
    },
    {
      problem: "Your retainer agency calls every video they ship 'a tested angle' and bills $4K-$15K/month",
      solution:
        "Two videos a month is not a tested angle. Ask your agency: how many variations did you ship for that hook? If the answer is under 30, you paid for video production, not for a test. Batch is engineered to ship 50-100+ variations of every angle in the same delivery — which is the only way the test is real.",
    },
    {
      problem: "You can't tell which line item in the agency invoice is 'creative production' versus 'media management' versus 'reporting'",
      solution:
        "That ambiguity is intentional. It makes it impossible to do per-angle math. Batch is a flat-fee, single-line invoice: Flat fee. 300 ads / 3 angles at $1,497. 500 ads / 5 angles at $2,497. 1,000 ads / 10 angles at $3,997. Cost-per-angle is just (price ÷ angles). No interpretation required.",
    },
    {
      problem: "Your in-house production cost feels 'free' because it's salaried — but the per-angle math is brutal",
      solution:
        "An in-house video producer at $70K + benefits who ships 8 videos a quarter is costing roughly $11K-$14K per video, fully loaded. At 30 videos to test one angle, that's $330K-$420K per fully tested angle — before you've shipped a single batch refresh. Salaried production is not free; it is the most expensive way to buy creative volume.",
    },
    {
      problem: "You assumed batch was 'lower quality' because the per-ad price is so much lower",
      solution:
        "Per-ad price is low because the production system is engineered for batch — not because we cut corners. Same scripts (vertical-researched), same recording quality (your real face, your real footage), same review process. The cost difference comes from compressing a 6-week sprint into 24 hours of production time, not from quality reduction.",
    },
  ],
  comparison: {
    headers: ["Cost Component", "Prestyj Batch (500 ads / 5 angles)", "Typical UGC Creators Path"],
    rows: [
      {
        feature: "Headline price",
        prestyj: "$2,497 flat",
        others: "$150-$400per video",
      },
      {
        feature: "Variations per tested angle",
        prestyj: "≈100",
        others: "1-8",
      },
      {
        feature: "Cost per fully tested angle",
        prestyj: "≈$500",
        others: "$3,000-$8,000 per angle (one creator, limited variation)",
      },
      {
        feature: "Time-to-first-test",
        prestyj: "4 days from kickoff",
        others: "14-45 days",
      },
      {
        feature: "Refresh cadence cost",
        prestyj: "New batch when you need it",
        others: "Recurring monthly retainer or per-video billing",
      },
      {
        feature: "Vertical-specific script research",
        prestyj: "Included",
        others: "Extra or skipped",
      },
      {
        feature: "Effective CPL impact",
        prestyj: "$8-$22",
        others: "$60-$180",
      },
    ],
  },
  faq: [
    {
      question: "How do you calculate cost per tested ad angle?",
      answer:
        "(Total cost to ship enough variations of one hook to exit Meta's learning phase) ÷ (number of distinct angles in that delivery). For batch at the 500-ad / 5-angle tier: $2,497 ÷ 5 = ≈$500/angle. For an agency shipping 1 angle/month at $5K retainer: $5,000/angle (and that's only one angle in 30 days). For Fiverr assembling 30-50 variations of one hook at $200/video: $6,000-$10,000/angle. The math is what makes batch viable for coaches.",
    },
    {
      question: "Doesn't more variations just mean more noise?",
      answer:
        "No — it means cleaner signal. Meta and TikTok algorithms are designed to find the best-performing creative inside an ad set when given enough options. Below ~30 variations they cannot reliably differentiate. Above ~50 they consistently find a winner. 'More variations = noise' was true in 2018 manual-bidding. In 2026 algorithmic bidding, more variations = better optimization. Coaches who ship batch consistently report $8-$22 after the algorithm has enough fuel.",
    },
    {
      question: "Are the 100 variations per angle actually unique or just minor edits?",
      answer:
        "Both — and that's the point. Meta's algorithm responds to varied hooks, varied B-roll cuts, varied CTAs, varied first-3-second framing, and varied copy lengths. A '100 variation' angle is engineered to vary along all those axes so the algorithm can find the precise combination that hits your buyer. Trivial visual edits do not move the needle; structural variations do, and batch ships both.",
    },
    {
      question: "What about coaches who only need to test 1 angle?",
      answer:
        "Then the 300-ad / 3-angle tier at $1,497 still wins on per-angle math (≈$500/angle). But realistically, coaches almost never need only one angle. Different sub-audiences, different offers, different funnel stages, different times of year all need different hooks. Most coaches land at 5-10 angles within their first quarter on paid social.",
    },
    {
      question: "Where does the fatigue tax come into the math?",
      answer:
        "The hidden cost of running coach ads is creative fatigue tax — your CPL doubles every 3 weeks until you ship fresh creative. Cost per tested angle has to be re-paid every 30-60 days because winning angles fatigue. Batch math: a refresh batch is the same flat fee. Agency math: every refresh resets the retainer clock. Over 12 months the cost gap widens dramatically — most coaches who run continuous paid social see batch save 60-85% of fully-loaded creative cost over a calendar year.",
    },
  ],
  cta: {
    headline: "Run the Math for Coaches: ≈$500 Per Tested Angle.",
    subheadline:
      "300-1,000 scripted ads, vertical-researched for coaches, your real face, 24-hour delivery. Flat fee from $1,497 — the only pricing model where per-tested-angle math actually works.",
    buttonText: "Book a Demo",
    buttonHref: "/book-demo",
    footnote: "One-time pricing from $1,497 · No retainer · Flat fee. 300 ads / 3 angles at $1,497. 500 ads / 5 angles at $2,497. 1,000 ads / 10 angles at $3,997.",
  },
};
