import type { BestForPageContent } from "./types";

// AUTO-GENERATED by scripts/generate-batch-video-ad-organic-matrix.ts
// Vertical: Consultants · Angle: creative testing
export const creativeTestingForConsultants: BestForPageContent = {
  slug: "creative-testing-for-consultants",
  niche: {
    name: "Creative Testing for Consultants",
    shortName: "Consultants",
    description: "a paid-social creative testing plan for consultants, advisors, and expert service providers selling audits, retainers, projects, and advisory calls.",
  },
  meta: {
    title: "Creative Testing for Consultants | Paid Social Ad Matrix",
    description: "Creative testing for consultants using a structured matrix of hooks, buyer pains, seasonal triggers, and compliance-aware video ad variations.",
    keywords: [
      "creative testing for consultants",
      "ad creative testing for consultants",
      "consultants facebook ad creative testing",
      "consultants paid social creative testing",
      "consultants ad fatigue solution",
      "video ad testing for consultants",
    ],
  },
  hero: {
    badge: "Creative Testing for Consultants",
    headline: "Consultants Should Not Test One Ad at a Time.",
    headlineAccent: "Test the angle matrix instead.",
    subheadline: "A useful consultant creative test compares buyer problems, timing triggers, offers, objections, and proof. Prestyj supplies the video variation library so your media buyer can find signal without waiting on weekly production.",
  },
  whyBestFor: [
    {
      icon: "Target",
      title: "Test buyer problems as separate hypotheses.",
      description: "For consultants, the first hypotheses should include: Prospects need to feel the problem before they care about your framework. Referrals hide which message would scale beyond your network. Authority ads must test insight, specificity, and trust without sounding generic. Each needs its own lane so the account can show what deserves budget.",
    },
    {
      icon: "Zap",
      title: "Test first-three-second hooks, not just finished concepts.",
      description: "The same offer can win or lose based on the opening. Examples worth testing include The expensive mistake hook, The audit teardown hook, The hidden cost of status quo hook, The framework in 30 seconds hook.",
    },
    {
      icon: "Clock",
      title: "Match creative drops to market timing.",
      description: "Consultant demand is shaped by Q1 planning, budget season, industry events, end-of-quarter pipeline pushes. Creative testing works better when those triggers become test lanes before demand peaks.",
    },
    {
      icon: "DollarSign",
      title: "Read results through unit economics.",
      description: "$3,000-$50,000 project or retainer value. That means the best creative test is not the prettiest ad — it is the angle that creates profitable booked opportunities.",
    },
    {
      icon: "Shield",
      title: "Keep every test within compliance boundaries.",
      description: "Avoid guaranteed business outcomes, revenue claims, or confidential client references.",
    },
  ],
  painPoints: [
    {
      problem: "Your creative test is too small to produce reliable signal.",
      solution: "Use a 100-ad batch for one focused problem, 300 ads for three problem lanes, 500 for the recommended matrix, or 1,000 for a full-market sprint.",
    },
    {
      problem: "Your current ads blur too many consultant buyer motivations together.",
      solution: "Separate the test into pain, timing, trust, price, and status quo lanes. That keeps consultants results readable instead of averaging every buyer into one generic message.",
    },
    {
      problem: "Your media buyer cannot scale because the creative library runs out.",
      solution: "Batch production creates enough adjacent variants to refresh winning lanes before the original ad fatigues.",
    },
    {
      problem: "Your status quo is still LinkedIn posts, referrals, and boutique lead-gen agencies.",
      solution: "Own the learning loop by building a creative library you can test, analyze, and reuse instead of renting attention from the same crowded sources.",
    },
    {
      problem: "Your team does not have a repeatable script matrix.",
      solution: "Prestyj writes the hook, body, objection, proof, and CTA variations, then edits one recording into finished ads.",
    },
  ],
  comparison: {
    headers: ["Testing Layer", "Structured Creative Test", "Thin Creative Test"],
    rows: [
      {
        feature: "Hypotheses",
        prestyj: "Pain, timing, proof, objection, CTA, and status quo lanes",
        others: "One or two broad concepts",
      },
      {
        feature: "Vertical specificity",
        prestyj: "Consultants economics, triggers, and compliance notes built in",
        others: "Generic paid-social best practices",
      },
      {
        feature: "Refresh plan",
        prestyj: "Adjacent variants ready when a lane wins",
        others: "Start a new brief after fatigue appears",
      },
      {
        feature: "Cost lens",
        prestyj: "$3,000-$50,000 project or retainer value",
        others: "Per-video cost without angle-level learning",
      },
      {
        feature: "Next step",
        prestyj: "Scale the winning problem lane with fresh variants",
        others: "Guess which single ad to remake",
      },
    ],
  },
  faq: [
    {
      question: "What should a creative test for consultants include?",
      answer: "It should include separate hypotheses for buyer pains, timing triggers, proof, objections, offers, and CTAs. For consultants, strong starting points include The expensive mistake hook, The audit teardown hook, The hidden cost of status quo hook, The framework in 30 seconds hook.",
    },
    {
      question: "How many ads do I need for a creative test?",
      answer: "Use 100 ads for first signal around one problem, 300 for three problem lanes, 500 for the recommended matrix, and 1,000 for a full sprint across many buyer motivations.",
    },
    {
      question: "How is this different from batch video ads for consultants?",
      answer: "This page focuses on the testing methodology. The batch video ads page focuses on the production service and deliverables for consultants. Both point to the same pricing because the production system powers the test.",
    },
    {
      question: "Does Prestyj analyze the ad account?",
      answer: "No. Prestyj creates the creative library. Your media buyer or agency manages launch structure, budgets, reporting, and optimization.",
    },
    {
      question: "What compliance issue matters most for consultants creative testing?",
      answer: "Avoid guaranteed business outcomes, revenue claims, or confidential client references.",
    },
  ],
  cta: {
    headline: "Build a consultant Creative Testing Matrix.",
    subheadline: "Turn one recording into enough consultants ads to test buyer problems, timing triggers, objections, proof, and CTAs.",
    buttonText: "Pick a Batch Size",
    buttonHref: "/batch-video-ads#pricing",
    footnote: "Creative production only · Media buying not included",
  },
};
