import type { BestForPageContent } from "./types";

// AUTO-GENERATED by scripts/generate-batch-video-ad-organic-matrix.ts
// Vertical: Personal Brands · Angle: creative testing
export const creativeTestingForPersonalBrands: BestForPageContent = {
  slug: "creative-testing-for-personal-brands",
  niche: {
    name: "Creative Testing for Personal Brands",
    shortName: "Personal Brands",
    description: "a paid-social creative testing plan for founders, executives, coaches, and operators using their face and point of view to drive paid demand.",
  },
  meta: {
    title: "Creative Testing for Personal Brands | Paid Social Ad Matrix",
    description: "Creative testing for personal brands using a structured matrix of hooks, buyer pains, seasonal triggers, and compliance-aware video ad variations.",
    keywords: [
      "creative testing for personal brands",
      "ad creative testing for personal-brands",
      "personal brands facebook ad creative testing",
      "personal brands paid social creative testing",
      "personal brands ad fatigue solution",
      "video ad testing for personal-brands",
    ],
  },
  hero: {
    badge: "Creative Testing for Personal Brands",
    headline: "Personal Brands Should Not Test One Ad at a Time.",
    headlineAccent: "Test the angle matrix instead.",
    subheadline: "A useful personal brand creative test compares buyer problems, timing triggers, offers, objections, and proof. Prestyj supplies the video variation library so your media buyer can find signal without waiting on weekly production.",
  },
  whyBestFor: [
    {
      icon: "Target",
      title: "Test buyer problems as separate hypotheses.",
      description: "For personal brands, the first hypotheses should include: Your face is the differentiator, but one hero ad cannot carry every audience. Organic content is rarely cut into enough paid variants to learn at scale. Authority requires repeated angles, not one generic brand manifesto. Each needs its own lane so the account can show what deserves budget.",
    },
    {
      icon: "Zap",
      title: "Test first-three-second hooks, not just finished concepts.",
      description: "The same offer can win or lose based on the opening. Examples worth testing include The unpopular opinion hook, The lesson from a client call hook, The founder story proof hook, The direct invitation hook.",
    },
    {
      icon: "Clock",
      title: "Match creative drops to market timing.",
      description: "Personal brand demand is shaped by launches, speaking events, book releases, fundraising or hiring pushes. Creative testing works better when those triggers become test lanes before demand peaks.",
    },
    {
      icon: "DollarSign",
      title: "Read results through unit economics.",
      description: "$500-$50,000 per booked call, cohort, sponsorship, service, or advisory relationship. That means the best creative test is not the prettiest ad — it is the angle that creates profitable booked opportunities.",
    },
    {
      icon: "Shield",
      title: "Keep every test within compliance boundaries.",
      description: "Avoid unsupported earnings, investment, health, or transformation claims tied to personal authority.",
    },
  ],
  painPoints: [
    {
      problem: "Your creative test is too small to produce reliable signal.",
      solution: "Use a 100-ad batch for one focused problem, 300 ads for three problem lanes, 500 for the recommended matrix, or 1,000 for a full-market sprint.",
    },
    {
      problem: "Your current ads blur too many personal brand buyer motivations together.",
      solution: "Separate the test into pain, timing, trust, price, and status quo lanes. That keeps personal brands results readable instead of averaging every buyer into one generic message.",
    },
    {
      problem: "Your media buyer cannot scale because the creative library runs out.",
      solution: "Batch production creates enough adjacent variants to refresh winning lanes before the original ad fatigues.",
    },
    {
      problem: "Your status quo is still freelance editors and repurposed organic content.",
      solution: "Own the learning loop by building a creative library you can test, analyze, and reuse instead of renting attention from the same crowded sources.",
    },
    {
      problem: "Your team does not have a repeatable script matrix.",
      solution: "Prestyj writes the hook, body, objection, proof, and CTA variations, then edits one recording into finished ads.",
    },
  ],
  comparison: {
    headers: ["Testing Layer", "Structured Creative Test", "Thin Creative Test"],
    rows: [
      {
        feature: "Hypotheses",
        prestyj: "Pain, timing, proof, objection, CTA, and status quo lanes",
        others: "One or two broad concepts",
      },
      {
        feature: "Vertical specificity",
        prestyj: "Personal Brands economics, triggers, and compliance notes built in",
        others: "Generic paid-social best practices",
      },
      {
        feature: "Refresh plan",
        prestyj: "Adjacent variants ready when a lane wins",
        others: "Start a new brief after fatigue appears",
      },
      {
        feature: "Cost lens",
        prestyj: "$500-$50,000 per booked call, cohort, sponsorship, service, or advisory relationship",
        others: "Per-video cost without angle-level learning",
      },
      {
        feature: "Next step",
        prestyj: "Scale the winning problem lane with fresh variants",
        others: "Guess which single ad to remake",
      },
    ],
  },
  faq: [
    {
      question: "What should a creative test for personal brands include?",
      answer: "It should include separate hypotheses for buyer pains, timing triggers, proof, objections, offers, and CTAs. For personal brands, strong starting points include The unpopular opinion hook, The lesson from a client call hook, The founder story proof hook, The direct invitation hook.",
    },
    {
      question: "How many ads do I need for a creative test?",
      answer: "Use 100 ads for first signal around one problem, 300 for three problem lanes, 500 for the recommended matrix, and 1,000 for a full sprint across many buyer motivations.",
    },
    {
      question: "How is this different from batch video ads for personal brands?",
      answer: "This page focuses on the testing methodology. The batch video ads page focuses on the production service and deliverables for personal brands. Both point to the same pricing because the production system powers the test.",
    },
    {
      question: "Does Prestyj analyze the ad account?",
      answer: "No. Prestyj creates the creative library. Your media buyer or agency manages launch structure, budgets, reporting, and optimization.",
    },
    {
      question: "What compliance issue matters most for personal brands creative testing?",
      answer: "Avoid unsupported earnings, investment, health, or transformation claims tied to personal authority.",
    },
  ],
  cta: {
    headline: "Build a personal brand Creative Testing Matrix.",
    subheadline: "Turn one recording into enough personal brands ads to test buyer problems, timing triggers, objections, proof, and CTAs.",
    buttonText: "Pick a Batch Size",
    buttonHref: "/batch-video-ads#pricing",
    footnote: "Creative production only · Media buying not included",
  },
};
