import type { BestForPageContent } from "./types";

// AUTO-GENERATED by scripts/generate-batch-video-ad-organic-matrix.ts
// Vertical: Dentists · Angle: creative testing
export const creativeTestingForDentists: BestForPageContent = {
  slug: "creative-testing-for-dentists",
  niche: {
    name: "Creative Testing for Dentists",
    shortName: "Dentists",
    description: "a paid-social creative testing plan for dental practices marketing implants, Invisalign, emergency dentistry, hygiene, and cosmetic cases.",
  },
  meta: {
    title: "Creative Testing for Dentists | Paid Social Ad Matrix",
    description: "Creative testing for dentists using a structured matrix of hooks, buyer pains, seasonal triggers, and compliance-aware video ad variations.",
    keywords: [
      "creative testing for dentists",
      "ad creative testing for dentists",
      "dentists facebook ad creative testing",
      "dentists paid social creative testing",
      "dentists ad fatigue solution",
      "video ad testing for dentists",
    ],
  },
  hero: {
    badge: "Creative Testing for Dentists",
    headline: "Dentists Should Not Test One Ad at a Time.",
    headlineAccent: "Test the angle matrix instead.",
    subheadline: "A useful dentist creative test compares buyer problems, timing triggers, offers, objections, and proof. Prestyj supplies the video variation library so your media buyer can find signal without waiting on weekly production.",
  },
  whyBestFor: [
    {
      icon: "Target",
      title: "Test buyer problems as separate hypotheses.",
      description: "For dentists, the first hypotheses should include: Implants, Invisalign, emergency, and hygiene patients have different anxieties. Dental ads must build trust quickly without sounding like medical overclaiming. One generic new-patient special wastes budget on the wrong case mix. Each needs its own lane so the account can show what deserves budget.",
    },
    {
      icon: "Zap",
      title: "Test first-three-second hooks, not just finished concepts.",
      description: "The same offer can win or lose based on the opening. Examples worth testing include The missing tooth confidence hook, The clear aligner before photos hook, The same-day emergency relief hook, The insurance benefits expire hook.",
    },
    {
      icon: "Clock",
      title: "Match creative drops to market timing.",
      description: "Dentist demand is shaped by benefits reset, wedding season, back to school, year-end insurance use. Creative testing works better when those triggers become test lanes before demand peaks.",
    },
    {
      icon: "DollarSign",
      title: "Read results through unit economics.",
      description: "$150 hygiene patient → $4,000-$35,000 implant or cosmetic case. That means the best creative test is not the prettiest ad — it is the angle that creates profitable booked opportunities.",
    },
    {
      icon: "Shield",
      title: "Keep every test within compliance boundaries.",
      description: "Avoid clinical outcome guarantees, before-after implications without consent, or claims that conflict with dental advertising rules.",
    },
  ],
  painPoints: [
    {
      problem: "Your creative test is too small to produce reliable signal.",
      solution: "Use a 100-ad batch for one focused problem, 300 ads for three problem lanes, 500 for the recommended matrix, or 1,000 for a full-market sprint.",
    },
    {
      problem: "Your current ads blur too many dentist buyer motivations together.",
      solution: "Separate the test into pain, timing, trust, price, and status quo lanes. That keeps dentists results readable instead of averaging every buyer into one generic message.",
    },
    {
      problem: "Your media buyer cannot scale because the creative library runs out.",
      solution: "Batch production creates enough adjacent variants to refresh winning lanes before the original ad fatigues.",
    },
    {
      problem: "Your status quo is still dental PPC agencies and discount new-patient offers.",
      solution: "Own the learning loop by building a creative library you can test, analyze, and reuse instead of renting attention from the same crowded sources.",
    },
    {
      problem: "Your team does not have a repeatable script matrix.",
      solution: "Prestyj writes the hook, body, objection, proof, and CTA variations, then edits one recording into finished ads.",
    },
  ],
  comparison: {
    headers: ["Testing Layer", "Structured Creative Test", "Thin Creative Test"],
    rows: [
      {
        feature: "Hypotheses",
        prestyj: "Pain, timing, proof, objection, CTA, and status quo lanes",
        others: "One or two broad concepts",
      },
      {
        feature: "Vertical specificity",
        prestyj: "Dentists economics, triggers, and compliance notes built in",
        others: "Generic paid-social best practices",
      },
      {
        feature: "Refresh plan",
        prestyj: "Adjacent variants ready when a lane wins",
        others: "Start a new brief after fatigue appears",
      },
      {
        feature: "Cost lens",
        prestyj: "$150 hygiene patient → $4,000-$35,000 implant or cosmetic case",
        others: "Per-video cost without angle-level learning",
      },
      {
        feature: "Next step",
        prestyj: "Scale the winning problem lane with fresh variants",
        others: "Guess which single ad to remake",
      },
    ],
  },
  faq: [
    {
      question: "What should a creative test for dentists include?",
      answer: "It should include separate hypotheses for buyer pains, timing triggers, proof, objections, offers, and CTAs. For dentists, strong starting points include The missing tooth confidence hook, The clear aligner before photos hook, The same-day emergency relief hook, The insurance benefits expire hook.",
    },
    {
      question: "How many ads do I need for a creative test?",
      answer: "Use 100 ads for first signal around one problem, 300 for three problem lanes, 500 for the recommended matrix, and 1,000 for a full sprint across many buyer motivations.",
    },
    {
      question: "How is this different from batch video ads for dentists?",
      answer: "This page focuses on the testing methodology. The batch video ads page focuses on the production service and deliverables for dentists. Both point to the same pricing because the production system powers the test.",
    },
    {
      question: "Does Prestyj analyze the ad account?",
      answer: "No. Prestyj creates the creative library. Your media buyer or agency manages launch structure, budgets, reporting, and optimization.",
    },
    {
      question: "What compliance issue matters most for dentists creative testing?",
      answer: "Avoid clinical outcome guarantees, before-after implications without consent, or claims that conflict with dental advertising rules.",
    },
  ],
  cta: {
    headline: "Build a dentist Creative Testing Matrix.",
    subheadline: "Turn one recording into enough dentists ads to test buyer problems, timing triggers, objections, proof, and CTAs.",
    buttonText: "Pick a Batch Size",
    buttonHref: "/batch-video-ads#pricing",
    footnote: "Creative production only · Media buying not included",
  },
};
