import type { BestForPageContent } from "./types";

export const videoAdsForRoofers: BestForPageContent = {
  slug: "video-ads-for-roofers",
  niche: {
    name: "Video Ads for Roofers",
    shortName: "Roofers",
    description:
      "Roofing contractors using batch video ad creative testing to dominate storm-chasing windows, insurance claim leads, and retail roof replacement demand on Facebook and Instagram.",
  },
  meta: {
    title: "500 Roofing Video Ads in 24 Hours (From $1,497) | PRESTYJ",
    description:
      "Storm hit Tuesday? Your ads ship Wednesday. 300-1,000 scripted hail, wind, and retail reroof video ads with your real face, in 24 hours. From $1,497.",
    keywords: [
      "video ads for roofers",
      "facebook ads for roofing companies",
      "roofing company video marketing",
      "storm chasing video ads",
      "hail damage facebook ads",
      "roofer lead generation video",
      "roofing ad creative",
      "done for you roofer ads",
    ],
  },
  hero: {
    badge: "Batch Video Ads for Roofers",
    headline: "Storm Hit on Tuesday. Your Ads Should Hit",
    headlineAccent: "by Wednesday — Not in Three Weeks.",
    subheadline:
      "Hail windows close in 10 days. Wind events close in 30. By the time your marketing agency ships one new ad, the adjusters have already routed the neighborhood to someone else. Prestyj turns one 20-minute selfie recording into 300–1,000 scripted vertical video ads — storm-specific, zip-code specific, hail vs. wind specific — delivered in 24 hours so you own the window while it's open.",
  },
  whyBestFor: [
    {
      icon: "CloudRain",
      title: "Storm windows are 10–30 days. Retainer agencies ship ads in 14.",
      description:
        "A hail-hit zip code is a gold rush that collapses inside two weeks. You cannot win the window with an agency that 'workshops creative' on a 14-day cycle. Prestyj delivers 300–1,000 ad variations within 24 hours of receiving footage — meaning you can record Monday, ship ads Tuesday, and be on adjuster appointments by Wednesday.",
    },
    {
      icon: "Target",
      title: "Hail, wind, and tree-damage leads are three completely different creatives",
      description:
        "Hail damage claims lean on 'free inspection, we work with your adjuster, no out-of-pocket.' Wind damage leans on 'missing shingles on the back of your roof you can't see from the ground.' Tree impact leans on emergency tarp-and-tarp. A single retainer agency ships one 'storm damage' ad. Batch production lets you ship three event-specific tracks and find out which converts in your market.",
    },
    {
      icon: "Home",
      title: "'Your neighbor just got a new roof' is the highest-converting local hook in home services",
      description:
        "Neighborhood proof beats every other angle in roofing. Drone shots of recent installs, 'we did 7 roofs on this street last month,' 'three houses on [cross-street] filed claims this week' — these hooks convert because roofing is a social proof decision. Batch production lets you ship zip-code-specific variations at scale instead of one generic 'serving [metro]' ad.",
    },
    {
      icon: "DollarSign",
      title: "One retail reroof pays for the entire batch 5x over",
      description:
        "Average retail reroof is $12,000–$25,000+. An insurance claim reroof is $15,000–$40,000. A single additional job generated by improved ad creative more than pays back the $1,497–$3,997 batch — and then every subsequent job is pure margin on that creative investment.",
    },
    {
      icon: "Zap",
      title: "You don't need another canvasser. You need reach.",
      description:
        "Door-knocking still works — but it scales with headcount. Paid social with strong creative scales with budget. One batch, one ad account, and a competent media buyer can reach every homeowner in a damaged zip code in 48 hours. No D2D team can match that reach, and every lead generated on paid social is already pre-qualified by click intent.",
    },
  ],
  painPoints: [
    {
      problem: "You can't get new creative live fast enough when a storm hits your service area",
      solution:
        "Turnaround is the entire product. We deliver 300–1,000 variations 24 hours after you send footage. That means you can keep one pre-scripted 'storm event' shoot on file and ship event-specific ads the morning after any major weather event in your market — before your competition even calls their agency.",
    },
    {
      problem: "Your ads look identical to every other roofer in your zip code",
      solution:
        "We write direct-response scripts that name specific local details — 'if you live in [neighborhood] and your roof is more than 12 years old, here's what adjusters are finding on shingles like yours,' 'drone footage from a house on [street] last week showed damage the homeowner never would have seen.' Specific always beats generic in home services. Retainer agencies write generic because specific doesn't scale across their client roster. Batch makes specific cheap.",
    },
    {
      problem: "Insurance adjusters are denying claims and homeowners are getting discouraged before you can help",
      solution:
        "We build a dedicated track around adjuster-denial reversals: 'if your claim got denied and you were told there's no damage, here's what to ask for in a re-inspection.' These ads pull high-intent homeowners who are stuck in the claim process and bypass the 'tire kicker' top-of-funnel phase entirely. The people clicking already have damage and a claim open.",
    },
    {
      problem: "Your season is seasonal — you need leads in spring and fall and you get crickets in January",
      solution:
        "Off-season shouldn't be dead. A dedicated retail-reroof track in your batch ('is your roof over 15 years old? here's what insurance won't pay for — but a voluntary replacement now saves you $X') keeps leads flowing during wind-down months. We script both storm-chasing AND retail angles into the same batch so one purchase covers the full calendar year.",
    },
    {
      problem: "You tried Facebook ads, spent $3,000, got 4 leads, and quit",
      solution:
        "That's a creative volume problem, not a Facebook problem. The algorithm needs 30–50 fresh creatives per ad set to exit the learning phase. If you tested 3 ads, you never left learning. Batch production gives the algorithm what it needs to optimize — and the CPL almost always drops 40–70% in the first month when you feed it real creative diversity.",
    },
  ],
  comparison: {
    headers: ["Feature", "Prestyj Batch Video Ads", "Doing It Yourself or Hiring a Canvassing Team"],
    rows: [
      {
        feature: "Homes reached in a storm-hit zip code in 48 hours",
        prestyj: "Every homeowner on Facebook/Instagram in that zip",
        others: "Whatever your D2D team can physically knock in 2 days",
      },
      {
        feature: "Ad variations shipped per storm event",
        prestyj: "300–1,000 within 24 hours",
        others: "Zero — no creative production capacity",
      },
      {
        feature: "Cost per lead at scale",
        prestyj: "$15–$45 depending on market and event",
        others: "$80–$200+ per canvasser lead (labor + vehicles + overhead)",
      },
      {
        feature: "Hail vs wind vs retail angle testing",
        prestyj: "Three dedicated tracks in one batch",
        others: "Same pitch at every door",
      },
      {
        feature: "Works at night, weekends, off-hours",
        prestyj: "24/7 while ads are running",
        others: "Daylight, weekdays, weather-permitting",
      },
      {
        feature: "Off-season lead flow",
        prestyj: "Retail-reroof track runs year-round",
        others: "Canvassers dry up when storms stop",
      },
      {
        feature: "Cost structure",
        prestyj: "One-time $1,497 / $2,497 / $3,997",
        others: "$60K+/year per canvasser fully loaded",
      },
    ],
  },
  faq: [
    {
      question: "How fast can I actually get ads live after a storm hits?",
      answer:
        "Fastest real-world timeline: storm hits Monday night, you record 15–20 minutes of event-specific footage Tuesday morning addressing the specific event ('Hail hit [metro] last night — here's what you need to check before your adjuster comes out'), we deliver the batch Wednesday morning, you're running ads by Wednesday afternoon. If you have pre-scripted event footage already shot and on file with us, we can ship within 12 hours of your event request.",
    },
    {
      question: "Do these ads work for insurance claim leads specifically, or only retail?",
      answer:
        "Both, and you want both in the same batch. Insurance claim ads pull homeowners who already suspect damage and want help navigating the adjuster. Retail reroof ads pull homeowners whose roof is old but have no storm event — different audience, different copy, different urgency. A 500-ad batch (5 pain points) comfortably splits into 3 claim-side tracks (hail, wind, adjuster-denial reversal) and 2 retail tracks (age-based replacement, energy efficiency upgrade).",
    },
    {
      question: "My market is tiny and everyone already knows my company. Why would I pay for ads?",
      answer:
        "Brand recognition doesn't equal current-moment intent. Homeowners in your market know you exist, but they only think about you when their roof leaks. Paid video creative shows up in their feed when they're not thinking about it — with specific hooks that trigger 'wait, I did hear about [neighbor's] claim.' Small-market roofers with strong video ads outperform big-market roofers who rely only on trucks and Google Business because they stay top-of-mind between events.",
    },
    {
      question: "Can I include drone footage of my recent installs in these ads?",
      answer:
        "Yes — and you should. Drone B-roll is some of the highest-performing roofing ad content. When we send your shot list, we'll include a drone-footage request if you have recent installs or damage examples you can shoot. If not, we still write scripts that work with phone-camera B-roll (trucks, crews on roofs, shingle close-ups, finished product). Drone just amplifies what already works.",
    },
    {
      question: "What about contractor licensing requirements in my state for advertising?",
      answer:
        "We include your state license number and any required language (insurance-assistance disclaimers for states that restrict 'we'll pay your deductible' style offers — Texas, Louisiana, and others have rules here) directly in the ad scripts and on-screen text. Send us your license info and any state-specific disclosures and we bake them in before delivery. You review everything before it's finalized.",
    },
  ],
  cta: {
    headline: "Own the Storm Window. Run 500 Ads Before Your Competition Ships One.",
    subheadline:
      "One 20-minute recording. 300–1,000 scripted storm, claim, and retail reroof ads in 24 hours. Ship the morning after any event in your market — while the gold rush is still open.",
    buttonText: "Pick My Batch",
    buttonHref: "/batch-video-ads#pricing",
    footnote: "One-time pricing from $1,497 · 24-hour delivery · No retainer",
  },
};
