"use client";

// AUTO-GENERATED by scripts/generate-batch-video-ad-matrix.ts
import { ComparePageWrapper } from "@/components/sections/compare/ComparePageWrapper";
import { mediaBuyersVsFiverrVideoCompareData } from "@/lib/compare/data/prestyj-vs-fiverr-video-for-media-buyers";

export default function PrestyJVsFiverrForMediaBuyersPage() {
  return <ComparePageWrapper data={mediaBuyersVsFiverrVideoCompareData} />;
}
