export const AUDIT_COPY = {
  category: "Free business audit",
  headline: "Find the workflows costing you the most.",
  support:
    "See what drains time, slows sales, and hurts customers. Find where an AI agent can help first.",
  start: "Find my costly workflows",
  trust: "Free. About 4 minutes. See your top result before entering your email.",
  profileHeading: "Tell us about your business.",
  workflowHeading: "Where does work pile up?",
  workflowSupport: "Choose 3 to 5 workflows that take time or hold back sales.",
  hourlyCostQuestion: "What does one team hour cost?",
  hourlyCostHelp: "Include pay, taxes, tools, and overhead. Not sure? Use $65.",
  scoringIntro: "A few quick questions. Use your best estimate.",
  choiceError: "Choose one answer to continue.",
  previewLabel: "Your biggest leak",
  reportFormHeading: "Get the full report.",
  reportFormSupport: "See all 3 priorities, the best-fit agent, and your first fix plan.",
  followupConsent: "Send me three short follow-ups to help me use this report.",
  submit: "Send my report",
  pending: "Building your report...",
  success: "Your report is ready.",
  report: {
    yearlyCost: "Estimated yearly time cost",
    impact: "Business impact",
    readiness: "Ready for an AI agent",
    agentJob: "What the agent should do",
    ranked: "Your top 3 workflows",
    action: "Your first fix plan",
    blocker: "Fix this before you start",
    method: "How we worked this out",
    ctaHeading: "Want us to handle number one?",
    ctaSupport: "We will check the workflow, confirm the fit, and show the fastest path.",
    cta: "Review my top workflow",
    print: "Print or save report",
  },
} as const;
