import type { ComparePageData, CompareMetadata } from "../types";
import { createComparePage } from "@/lib/content-factory";

// AUTO-GENERATED by scripts/generate-social-vertical-matrix.ts
// Vertical: Coaches · Angle: Prestyj vs In-House Social Media Hire

const PRESTYJ_PRICING_FEATURES = [
  { text: "1,500+ posts/month across 7 platforms", included: true },
  { text: "Coaches-researched scripts, hooks, and frameworks", included: true },
  { text: "Voice-trained captions on your existing content", included: true },
  { text: "Daily multi-platform publishing (LinkedIn, Instagram, YouTube Shorts, X, +)", included: true },
  { text: "Weekly content calendar — approve in 15–30 min", included: true },
  { text: "Performance learning loop tunes future posts", included: true },
  { text: "Live in days — not 4–8 week onboarding", included: true },
  { text: "Month-to-month — cancel anytime, no contract", included: true },
];

export const coachesVsInHouseHireForCompareData: ComparePageData = createComparePage({
  slug: "prestyj-vs-in-house-hire-for-coaches",
  competitorName: "In-House Social Media Hire (for Coaches)",
  hero: {
    badge: "AI Content Engine vs In-House Hire",
    title: "Prestyj vs",
    titleAccent: "In-House Social Media Hire for Coaches",
    subtitle:
      "business, executive, and life coaches selling $2K–$25K coaching programs and group offers keep defaulting to in-house social media hire for social — and watching them ship 20–40 posts/month at 20–40 posts/month, 9–5, PTO + sick days. Prestyj is the AI content engine alternative: 1,500+ posts/month across 7 platforms, Coaches-researched, voice-trained, month-to-month from $3,000/mo flat.",
    description: "",
    keyStats: [
      { value: "$3K/mo vs $55K–$85K/year (fully loaded)", label: "AI engine vs in-house hire" },
      { value: "1,500+ vs 20–40", label: "Posts/month — Prestyj vs in-house hire" },
      { value: "7 vs 1–3", label: "Platforms covered" },
      { value: "Days vs 4–8 wks", label: "Onboarding time" },
    ],
  },
  pricing: {
    prestyj: {
      price: "$3,000",
      priceSubtext: "/month · 1,500+ posts · Coaches-researched",
      features: PRESTYJ_PRICING_FEATURES,
    },
    competitor: {
      price: "$55K–$85K",
      priceSubtext: "/year (fully loaded)",
      features: [
        { text: "20–40 posts/month, 9–5, PTO + sick days", included: true },
        { text: "Coaches-specific vertical research", included: false },
        { text: "Voice training on your existing content", included: false },
        { text: "1,500+ posts/month volume", included: false },
        { text: "7-platform daily publishing", included: false },
        { text: "Performance learning loop", included: false },
        { text: "Live in days, no long onboarding", included: false },
      ],
    },
  },
  features: [
    { feature: "Coaches-specific vertical research", prestyj: true, competitor: false, note: "In-House Social Media Hire does not research coaches pain points by default" },
    { feature: "Posts per month", prestyj: "1,500+", competitor: "20–40" },
    { feature: "Platforms covered", prestyj: "7 (LinkedIn, Instagram, YouTube Shorts, X, +)", competitor: "1–3 typical" },
    { feature: "Monthly cost", prestyj: "$3,000 flat", competitor: "$55K–$85K/year (fully loaded)" },
    { feature: "Cost per post", prestyj: "~$2", competitor: "$50–$750" },
    { feature: "Voice training on your existing content", prestyj: true, competitor: false },
    { feature: "Daily auto-publish", prestyj: true, competitor: false },
    { feature: "Long-term contract required", prestyj: false, competitor: true, note: "Employment contract — plus severance risk" },
    { feature: "Onboarding time", prestyj: "Days", competitor: "6–12 weeks (hiring + ramp)" },
    { feature: "Coverage", prestyj: "24/7/365", competitor: "9–5 + PTO + sick days" },
    { feature: "Performance learning loop", prestyj: true, competitor: false },
    { feature: "Risk of voice drift", prestyj: "Low — trained on your existing content", competitor: "Medium — depends on team turnover" },
  ],
  whySwitch: {
    title: "Why Coaches Pick the AI Content Engine Over In-House Social Media Hire",
    description:
      "A salaried in-house social media coordinator or manager — usually a 1–3 year experience hire making $55K–$85K fully loaded — responsible for posting, captions, and basic creative. For business, executive, and life coaches selling $2K–$25K coaching programs and group offers, the math stops working at scale.",
    reasons: [
      {
        icon: "Zap",
        title: "Volume that actually feeds the algorithm",
        description:
          "Coaches who post daily land 3–5× more discovery calls — but coaching delivery makes daily posting impossible without a content engine. In-House Hire cannot ship at 1,500+ posts/month — the unit of work they produce (20–40 posts/month, 9–5, pto + sick days) is fundamentally incompatible with the cadence the algorithms now reward for coaches.",
      },
      {
        icon: "DollarSign",
        title: "The math finally works for coaches",
        description:
          "the hidden cost of coaching is that every hour spent writing posts is an hour you're not delivering transformation — and one high-ticket client pays for an entire year of content. Prestyj's $3,000/month flat math puts cost per post at ~$2. In-House Hire math puts the same content at $50–$750 per post once you factor in management overhead, training, or turnover.",
      },
      {
        icon: "Clock",
        title: "Days to launch, not months of ramp",
        description:
          "In-House Hire requires 6–12 weeks to hire, onboard, and ramp before the first post ships. Prestyj's voice training and coaches-specific scripts mean daily publishing in days, not weeks.",
      },
      {
        icon: "Target",
        title: "Coaches-specific scripts vs generic in-house hire output",
        description:
          "Coaches live or die by voice — generic guru-bot content actively repels the high-ticket clients you actually want. Voice training on your existing posts, podcast clips, and program transcripts is non-negotiable. In-House Hire typically ships what you brief them on — they do not bring coaches vertical research to the table. Prestyj begins every engagement with a vertical research pass on current-quarter coaches hook patterns.",
      },
      {
        icon: "Shield",
        title: "Single accountable engine, not turnover risk",
        description:
          "Median tenure of a junior social hire is under 14 months — every departure resets voice training and content velocity. Prestyj is one engine, one voice, one standard — 1,500+ posts a month, every month.",
      },
    ],
  },
  relatedResources: [
    { title: "Done-For-You Social Media — the Service", description: "See the Prestyj content engine product", href: "/done-for-you-social-media", linkText: "Learn more" },
    { title: "Done-For-You Social Media for Coaches", description: "Coaches-specific offer page", href: "/best-for/done-for-you-social-for-coaches", linkText: "Read use case" },
    { title: "Social Volume Strategy for Coaches", description: "Cadence math and 2026 platform priorities", href: "/best-for/social-volume-strategy-for-coaches", linkText: "See the strategy" },
    { title: "Coaches Social Media Agency Alternative", description: "Alternative to traditional coaches social media agencies", href: "/alternatives/coaches-social-media-agency-alternative", linkText: "Compare" },
  ],
  cta: {
    title: "Coaches Pick the AI Content Engine Over In-House Social Media Hire.",
    description:
      "1,500+ coaches-researched posts a month across 7 platforms. One flat fee of $3,000/mo. Voice-trained. No contract. Live in days.",
    buttonText: "See How It Works for Coaches",
    buttonHref: "/done-for-you-social-media",
    disclaimer: "Month-to-month · No contract · 1,500+ posts/month",
  },
});

export const coachesVsInHouseHireForCompareDataMetadata: CompareMetadata = {
  slug: "prestyj-vs-in-house-hire-for-coaches",
  competitorName: "In-House Social Media Hire (for Coaches)",
  title: "PRESTYJ vs In-House Social Media Hire for Coaches (2026 Cadence Math)",
  description:
    "A salaried in-house social media coordinator or manager — usually a 1–3 year experience hire making $55K–$85K fully loaded — responsible for posting, captions, and basic creative. See full posts-per-month math and why business, executive, and life coaches selling $2K–$25K coaching programs and group offers pick the AI content engine from $3,000/mo over $55K–$85K/year (fully loaded).",
  keywords: [
    "prestyj vs in-house-hire for coaches",
    "in-house-hire alternative for coaches",
    "coaches in-house hire comparison",
    "social media for coaches",
    "coaches content production pricing",
    "in-house-hire for coaches alternative",
  ],
};
