import type { ComparePageData, CompareMetadata } from "../types";
import { createComparePage } from "@/lib/content-factory";

// AUTO-GENERATED by scripts/generate-batch-video-ad-matrix.ts
// Vertical: Plumbing Contractors · Angle: vs Fiverr Video Editors

const PRESTYJ_PRICING_FEATURES = [
  { text: "300-1,000 unique vertical video ads per batch", included: true },
  { text: "Scripts written for you (vertical-researched)", included: true },
  { text: "You record once in 15-20 min", included: true },
  { text: "24-hour turnaround", included: true },
  { text: "Hook + body + CTA variations", included: true },
  { text: "Your real face — not AI", included: true },
  { text: "No monthly subscription", included: true },
  { text: "Error revisions included", included: true },
];

export const plumbingContractorsVsFiverrVideoCompareData: ComparePageData = createComparePage({
  slug: "prestyj-vs-fiverr-video-for-plumbing-contractors",
  competitorName: "Fiverr Video Editors (for Plumbing)",
  hero: {
    badge: "Fiverr Lottery vs Plumbing Batch System",
    title: "Prestyj vs",
    titleAccent: "Fiverr Video Editors for Plumbing",
    subtitle:
      "Your Fiverr editor has never written a sewer-replacement script. Prestyj's batch ships 50 plumbing-specific scripts in one delivery. Prestyj is the alternative: Plumbing-researched scripts, your real face, 300-1,000 ads in 24 hours, flat fee from $1,497.",
    description: "",
    keyStats: [
      { value: "300-1,000", label: "Prestyj ads per batch" },
      { value: "$25-$500", label: "Fiverr Video Editors starting price" },
      { value: "24 hrs", label: "Prestyj turnaround" },
    ],
  },
  pricing: {
    prestyj: {
      price: "$1,497 – $3,997",
      priceSubtext: "One-time · 300-1,000 ads · Plumbing-researched",
      features: PRESTYJ_PRICING_FEATURES,
    },
    competitor: {
      price: "$25-$500",
      priceSubtext: "per gig",
      features: [
        { text: "Marketplace of thousands of sellers", included: true },
        { text: "Low entry price per gig", included: true },
        { text: "Vertical-specific scripting", included: false },
        { text: "Quality consistent across deliverables", included: false },
        { text: "Volume per engagement (300+ ads)", included: false },
        { text: "24-hour turnaround SLA", included: false },
      ],
    },
  },
  features: [
    { feature: "Scripts researched for Plumbing pain points", prestyj: true, competitor: false, note: "Fiverr Video Editors does not research your vertical by default" },
    { feature: "Uses your real face / actual company", prestyj: true, competitor: "Sometimes" },
    { feature: "Variations per engagement", prestyj: "300-1,000", competitor: "1-5 per gig" },
    { feature: "Turnaround SLA", prestyj: "24 hrs guaranteed", competitor: "3-14 days, often slipped" },
    { feature: "Pricing model", prestyj: "One-time flat", competitor: "Per video / per gig" },
    { feature: "Cost per ad (at 500 ads)", prestyj: "≈$5", competitor: "$25-$500 each" },
    { feature: "Cost per fully tested angle", prestyj: "≈$500", competitor: "$9K-$15K" },
    { feature: "Built for Plumbing ad fatigue cycles", prestyj: true, competitor: false },
    { feature: "Vertical research bundled", prestyj: true, competitor: false },
  ],
  whySwitch: {
    title: "Why Plumbing Pick Batch Over Fiverr Video Editors",
    description: "Your Fiverr editor has never written a sewer-replacement script. Prestyj's batch ships 50 plumbing-specific scripts in one delivery.",
    reasons: [
      {
        icon: "Zap",
        title: "Sewer-line jobs and water-heater jobs are different audiences — and your one ad treats them as one",
        description:
          "Fiverr Video Editors cannot fix this. The unit they ship (per-video, per-gig, per-month) is fundamentally incompatible with the cadence paid social actually requires (50+ creatives per ad set to exit learning).",
      },
      {
        icon: "DollarSign",
        title: "Per-angle math finally works",
        description:
          "The hidden cost is mismatched-intent traffic — generic plumbing ads pull tire-kickers while specific 'water-heater replacement' or 'slab leak' ads pull buyers. Batch math at the 500-ad tier puts cost per fully tested angle at ≈$500. Fiverr Video Editors math puts it at $9K-$15K to assemble enough variations.",
      },
      {
        icon: "Clock",
        title: "Event-driven creative inside 24 hours",
        description:
          "Emergency leak ads vs preventive repipe ads need different creative — you ship one generic 'we do plumbing' video Fiverr Video Editors cycles cannot ship event-specific creative inside the window when it matters. Batch delivers in 24 hours from footage — meaning plumbing can finally compete on cadence.",
      },
      {
        icon: "Target",
        title: "Plumbing-specific scripts vs generic fiverr video editors output",
        description:
          "Your warranty pitch and your financing pitch never appear in the same ad rotation because you only have 2 ads Batch begins every engagement with a vertical research pass on highest-converting plumbing hook patterns from current-quarter ad libraries. Fiverr Video Editors typically ship what you brief them on — they do not bring vertical research to the table.",
      },
      {
        icon: "Shield",
        title: "Single team, single accountability",
        description:
          "Fiverr is a coin flip across thousands of sellers. Batch is one team, one standard, every delivery.",
      },
    ],
  },
  relatedResources: [
    { title: "Batch Video Ads — the Service", description: "See the Prestyj batch product", href: "/batch-video-ads", linkText: "Learn more" },
    { title: "Batch Video Ads for Plumbing Contractors", description: "Plumbing-specific use case", href: "/best-for/batch-video-ads-for-plumbing-contractors", linkText: "Read use case" },
    { title: "Cost Per Tested Ad Angle for Plumbing", description: "Full pricing math breakdown", href: "/best-for/cost-per-tested-ad-angle-for-plumbing-contractors", linkText: "See the math" },
    { title: "Plumbing Contractors Video Production Alternative", description: "Alternative to traditional plumbing video production", href: "/alternatives/plumbing-contractors-video-production-alternative", linkText: "Compare" },
  ],
  cta: {
    title: "Plumbing Pick Batch Over Fiverr Video Editors.",
    description:
      "300-1,000 plumbing-researched ads in 24 hours. One flat fee from $1,497. Your real face. No retainer.",
    buttonText: "Pick My Batch",
    buttonHref: "/batch-video-ads#pricing",
    disclaimer: "One-time payment · No subscription · 24-hour turnaround",
  },
});

export const plumbingContractorsVsFiverrVideoMetadata: CompareMetadata = {
  slug: "prestyj-vs-fiverr-video-for-plumbing-contractors",
  competitorName: "Fiverr Video Editors (for Plumbing)",
  title: "PRESTYJ vs Fiverr Video Editors for Plumbing (2026 Pricing Math)",
  description:
    "Your Fiverr editor has never written a sewer-replacement script. Prestyj's batch ships 50 plumbing-specific scripts in one delivery. See full per-angle pricing math and why plumbing pick batch from $1,497 over $25-$500per gig.",
  keywords: [
    "prestyj vs fiverr for plumbing-contractors",
    "fiverr alternative for plumbing-contractors",
    "plumbing fiverr comparison",
    "batch video ads vs fiverr",
    "plumbing video creative pricing",
    "fiverr for plumbing-contractors alternative",
  ],
};
