import type { ComparePageData, CompareMetadata } from "../types";
import { createComparePage } from "@/lib/content-factory";

// AUTO-GENERATED by scripts/generate-batch-video-ad-matrix.ts
// Vertical: Coaches · Angle: vs UGC Creators

const PRESTYJ_PRICING_FEATURES = [
  { text: "300-1,000 unique vertical video ads per batch", included: true },
  { text: "Scripts written for you (vertical-researched)", included: true },
  { text: "You record once in 15-20 min", included: true },
  { text: "24-hour turnaround", included: true },
  { text: "Hook + body + CTA variations", included: true },
  { text: "Your real face — not AI", included: true },
  { text: "No monthly subscription", included: true },
  { text: "Error revisions included", included: true },
];

export const coachesVsUgcCreatorVideoCompareData: ComparePageData = createComparePage({
  slug: "prestyj-vs-ugc-creator-video-for-coaches",
  competitorName: "UGC Creators (for Coaches)",
  hero: {
    badge: "UGC vs Founder-Led Coach Ads",
    title: "Prestyj vs",
    titleAccent: "UGC Creators for Coaches",
    subtitle:
      "A UGC creator pretending to be your student is not your offer. You are the offer. Prestyj is the alternative: Coaches-researched scripts, your real face, 300-1,000 ads in 24 hours, flat fee from $1,497.",
    description: "",
    keyStats: [
      { value: "300-1,000", label: "Prestyj ads per batch" },
      { value: "$150-$400", label: "UGC Creators starting price" },
      { value: "24 hrs", label: "Prestyj turnaround" },
    ],
  },
  pricing: {
    prestyj: {
      price: "$1,497 – $3,997",
      priceSubtext: "One-time · 300-1,000 ads · Coaches-researched",
      features: PRESTYJ_PRICING_FEATURES,
    },
    competitor: {
      price: "$150-$400",
      priceSubtext: "per video",
      features: [
        { text: "Real human creator (not AI)", included: true },
        { text: "Authentic-feeling style", included: true },
        { text: "Vertical-researched scripts", included: false },
        { text: "Uses your real face", included: false },
        { text: "Volume per engagement (300+ ads)", included: false },
        { text: "24-hour turnaround", included: false },
      ],
    },
  },
  features: [
    { feature: "Scripts researched for Coaches pain points", prestyj: true, competitor: false, note: "UGC Creators does not research your vertical by default" },
    { feature: "Uses your real face / actual brand", prestyj: true, competitor: false },
    { feature: "Variations per engagement", prestyj: "300-1,000", competitor: "1-3 per creator" },
    { feature: "Turnaround SLA", prestyj: "24 hrs guaranteed", competitor: "14-45 days" },
    { feature: "Pricing model", prestyj: "One-time flat", competitor: "Per video / per gig" },
    { feature: "Cost per ad (at 500 ads)", prestyj: "≈$5", competitor: "$200-$600 each" },
    { feature: "Cost per fully tested angle", prestyj: "≈$500", competitor: "$3K-$8K" },
    { feature: "Built for Coaches ad fatigue cycles", prestyj: true, competitor: false },
    { feature: "Vertical research bundled", prestyj: true, competitor: false },
  ],
  whySwitch: {
    title: "Why Coaches Pick Batch Over UGC Creators",
    description: "A UGC creator pretending to be your student is not your offer. You are the offer.",
    reasons: [
      {
        icon: "Zap",
        title: "Your face is the offer — but you only have 4 ad creatives in rotation",
        description:
          "UGC Creators cannot fix this. The unit they ship (per-video, per-gig, per-month) is fundamentally incompatible with the cadence paid social actually requires (50+ creatives per ad set to exit learning).",
      },
      {
        icon: "DollarSign",
        title: "Per-angle math finally works",
        description:
          "The hidden cost of running coach ads is creative fatigue tax — your CPL doubles every 3 weeks until you ship fresh creative. Batch math at the 500-ad tier puts cost per fully tested angle at ≈$500. UGC Creators math puts it at $3K-$8K per tested angle.",
      },
      {
        icon: "Clock",
        title: "Event-driven creative inside 24 hours",
        description:
          "Webinar registrations stalled because every prospect has seen your same hook 12 times UGC Creators cycles cannot ship event-specific creative inside the window when it matters. Batch delivers in 24 hours from footage — meaning coaches can finally compete on cadence.",
      },
      {
        icon: "Target",
        title: "Coaches-specific scripts vs generic ugc creators output",
        description:
          "VSL-only funnels are dying in 2026 — short-form ads now feed every booking call Batch begins every engagement with a vertical research pass on highest-converting coaches hook patterns from current-quarter ad libraries. UGC Creators typically ship what you brief them on — they do not bring vertical research to the table.",
      },
      {
        icon: "Shield",
        title: "Owner authenticity beats hired actors",
        description:
          "A UGC actress is not the owner of your business. Coaches buy from people, not models.",
      },
    ],
  },
  relatedResources: [
    { title: "Batch Video Ads — the Service", description: "See the Prestyj batch product", href: "/batch-video-ads", linkText: "Learn more" },
    { title: "Batch Video Ads for Coaches", description: "Coaches-specific use case", href: "/best-for/batch-video-ads-for-coaches", linkText: "Read use case" },
    { title: "Cost Per Tested Ad Angle for Coaches", description: "Full pricing math breakdown", href: "/best-for/cost-per-tested-ad-angle-for-coaches", linkText: "See the math" },
    { title: "Coaches Video Production Alternative", description: "Alternative to traditional coaches video production", href: "/alternatives/coaches-video-production-alternative", linkText: "Compare" },
  ],
  cta: {
    title: "Coaches Pick Batch Over UGC Creators.",
    description:
      "300-1,000 coaches-researched ads in 24 hours. One flat fee from $1,497. Your real face. No retainer.",
    buttonText: "Pick My Batch",
    buttonHref: "/batch-video-ads#pricing",
    disclaimer: "One-time payment · No subscription · 24-hour turnaround",
  },
});

export const coachesVsUgcCreatorVideoMetadata: CompareMetadata = {
  slug: "prestyj-vs-ugc-creator-video-for-coaches",
  competitorName: "UGC Creators (for Coaches)",
  title: "PRESTYJ vs UGC Creators for Coaches (2026 Pricing Math)",
  description:
    "A UGC creator pretending to be your student is not your offer. You are the offer. See full per-angle pricing math and why coaches pick batch from $1,497 over $150-$400per video.",
  keywords: [
    "prestyj vs ugc-creator for coaches",
    "ugc-creator alternative for coaches",
    "coaches ugc-creator comparison",
    "batch video ads vs ugc-creator",
    "coaches video creative pricing",
    "ugc-creator for coaches alternative",
  ],
};
