import type { ComparePageData, CompareMetadata } from "../types";
import { createComparePage } from "@/lib/content-factory";

// AUTO-GENERATED by scripts/generate-batch-video-ad-matrix.ts
// Vertical: HVAC Companies · Angle: vs Home Services UGC Creators

const PRESTYJ_PRICING_FEATURES = [
  { text: "300-1,000 unique vertical video ads per batch", included: true },
  { text: "Scripts written for you (vertical-researched)", included: true },
  { text: "You record once in 15-20 min", included: true },
  { text: "24-hour turnaround", included: true },
  { text: "Hook + body + CTA variations", included: true },
  { text: "Your real face — not AI", included: true },
  { text: "Month-to-month, no long-term contract", included: true },
  { text: "Error revisions included", included: true },
];

export const hvacCompaniesVsUgcCreatorVideoCompareData: ComparePageData = createComparePage({
  slug: "prestyj-vs-ugc-creator-video-for-hvac-companies",
  competitorName: "Home Services UGC Creators (for HVAC)",
  hero: {
    badge: "UGC Marketplace vs Owner-Led HVAC Ads",
    title: "Prestyj vs",
    titleAccent: "Home Services UGC Creators for HVAC",
    subtitle:
      "A UGC actress in her kitchen is not an HVAC technician. Homeowners trust the owner of the company they're letting into their attic — not a hired model. Prestyj is the alternative: HVAC-researched scripts, your real face, 300-1,000 ads in 24 hours, flat fee from $1,497.",
    description: "",
    keyStats: [
      { value: "300-1,000", label: "Prestyj ads per batch" },
      { value: "$200-$600", label: "Home Services UGC Creators starting price" },
      { value: "24 hrs", label: "Prestyj turnaround" },
    ],
  },
  pricing: {
    prestyj: {
      price: "$1,997",
      priceSubtext: "/mo Starter · ad budget + batch video ads + AI agents · tuned for HVAC",
      features: PRESTYJ_PRICING_FEATURES,
    },
    competitor: {
      price: "$200-$600",
      priceSubtext: "per video",
      features: [
        { text: "Real human creator (not AI)", included: true },
        { text: "Authentic-feeling style", included: true },
        { text: "Vertical-researched scripts", included: false },
        { text: "Uses your real face", included: false },
        { text: "Volume per engagement (300+ ads)", included: false },
        { text: "24-hour turnaround", included: false },
      ],
    },
  },
  features: [
    {
      feature: "Scripts researched for HVAC pain points",
      prestyj: true,
      competitor: false,
      note: "Home Services UGC Creators does not research your vertical by default",
    },
    { feature: "Uses your real face / actual company", prestyj: true, competitor: false },
    { feature: "Variations per engagement", prestyj: "300-1,000", competitor: "1-3 per creator" },
    { feature: "Turnaround SLA", prestyj: "24 hrs guaranteed", competitor: "14-45 days" },
    { feature: "Pricing model", prestyj: "One-time flat", competitor: "Per video / per gig" },
    { feature: "Cost per ad (at 500 ads)", prestyj: "≈$5", competitor: "$200-$600 each" },
    { feature: "Cost per fully tested angle", prestyj: "≈$500", competitor: "$3K-$8K" },
    { feature: "Built for HVAC ad fatigue cycles", prestyj: true, competitor: false },
    { feature: "Vertical research bundled", prestyj: true, competitor: false },
  ],
  whySwitch: {
    title: "Why HVAC Pick Batch Over Home Services UGC Creators",
    description:
      "A UGC actress in her kitchen is not an HVAC technician. Homeowners trust the owner of the company they're letting into their attic — not a hired model.",
    reasons: [
      {
        icon: "Zap",
        title:
          "Heat-wave Tuesday means peak demand on Wednesday — but your ads were last refreshed in March",
        description:
          "Home Services UGC Creators cannot fix this. The unit they ship (per-video, per-gig, per-month) is fundamentally incompatible with the cadence paid social actually requires (50+ creatives per ad set to exit learning).",
      },
      {
        icon: "DollarSign",
        title: "Per-angle math finally works",
        description:
          "The hidden cost of static creative for HVAC is missed weather windows — every heat event is a 7-day demand spike and your competition's ads are already running. Batch math at the 500-ad tier puts cost per fully tested angle at ≈$500. Home Services UGC Creators math puts it at $3K-$8K per tested angle.",
      },
      {
        icon: "Clock",
        title: "Event-driven creative inside 24 hours",
        description:
          "ServiceTitan tells you which job pays — it doesn't tell you which ad creative drove it Home Services UGC Creators cycles cannot ship event-specific creative inside the window when it matters. Batch delivers in 24 hours from footage — meaning hvac can finally compete on cadence.",
      },
      {
        icon: "Target",
        title: "HVAC-specific scripts vs generic home services ugc creators output",
        description:
          "Equipment financing offers convert 4x better in video — but you only have 2 financing creatives running Batch begins every engagement with a vertical research pass on highest-converting hvac hook patterns from current-quarter ad libraries. Home Services UGC Creators typically ship what you brief them on — they do not bring vertical research to the table.",
      },
      {
        icon: "Shield",
        title: "Owner authenticity beats hired actors",
        description:
          "A UGC actress is not the owner of your business. Hvac buy from people, not models.",
      },
    ],
  },
  relatedResources: [
    {
      title: "Batch Video Ads — the Service",
      description: "See the Prestyj batch product",
      href: "/batch-video-ads",
      linkText: "Learn more",
    },
    {
      title: "Batch Video Ads for Real Estate Teams",
      description: "How the batch system applies to real estate teams",
      href: "/best-for/batch-video-ads-for-real-estate-teams",
      linkText: "Read use case",
    },
    {
      title: "Cost Per Tested Ad Angle",
      description: "Full pricing math breakdown",
      href: "/best-for/cost-per-tested-ad-angle-for-real-estate-teams",
      linkText: "See the math",
    },
    {
      title: "Video Production Alternative",
      description: "Alternative to traditional video production",
      href: "/alternatives/real-estate-teams-video-production-alternative",
      linkText: "Compare",
    },
  ],
  proprietaryData: {
    heading: "Do HVAC companies get better ad learning from AI batches than individual UGC creators?",
    intro: "HVAC marketing depends on matching the right seasonal problem to the right homeowner segment at the right time. These benchmarks show why creative breadth and cost transparency matter more than the charm of a single creator video.",
    stats: [
      { statId: "ugc-ad-roi-vs-ai-batch-roi-ratio", analysis: "A stronger per-dollar return means HVAC teams can test more comfort, repair, financing, and maintenance messages for the same spend. The practical advantage is more shots at finding the offer that fills the board during peak and shoulder seasons." },
      { statId: "ugc-marketplace-hidden-cost-percent", analysis: "Hidden marketplace costs are especially painful when seasonal windows are short and every revision delays launch. HVAC companies should compare the complete path to a usable ad, not only the creator's base fee." },
      { statId: "bva-winner-rate-home-services", analysis: "Because only a minority of home-service ads win, buying one or two creator concepts is an optimistic strategy. Prestyj's batch approach fits the odds by generating enough variations for the market to reveal which homeowner concern actually converts." }
    ],
    footnote: "Figures are Prestyj production benchmarks (src/lib/statistics-data). Each value links to its sourced /stat page.",
  },
  cta: {
    title: "HVAC Pick Batch Over Home Services UGC Creators.",
    description:
      "300-1,000 hvac-researched ads in 24 hours. One flat fee from $1,497. Your real face. No retainer.",
    buttonText: "Book a Demo",
    buttonHref: "/book-demo",
    disclaimer: "One-time payment · No subscription · 24-hour turnaround",
  },
});

export const hvacCompaniesVsUgcCreatorVideoMetadata: CompareMetadata = {
  slug: "prestyj-vs-ugc-creator-video-for-hvac-companies",
  competitorName: "Home Services UGC Creators (for HVAC)",
  title: "Prestyj vs Home Services UGC Creators for HVAC (2026 Pricing Math)",
  description:
    "A UGC actress in her kitchen is not an HVAC technician. Homeowners trust the owner of the company they're letting into their attic — not a hired model. See full per-angle pricing math and why hvac pick batch from $1,497 over $200-$600per video.",
  keywords: [
    "prestyj vs ugc-creator for hvac-companies",
    "ugc-creator alternative for hvac-companies",
    "hvac ugc-creator comparison",
    "batch video ads vs ugc-creator",
    "hvac video creative pricing",
    "ugc-creator for hvac-companies alternative",
  ],
};
