"use client";

// AUTO-GENERATED by scripts/generate-batch-video-ad-matrix.ts
import { ComparePageWrapper } from "@/components/sections/compare/ComparePageWrapper";
import { agencyOwnersVsAiAvatarToolVideoCompareData } from "@/lib/compare/data/prestyj-vs-ai-avatar-tool-video-for-agency-owners";

export default function PrestyJVsAiAvatarToolForAgencyOwnersPage() {
  return <ComparePageWrapper data={agencyOwnersVsAiAvatarToolVideoCompareData} />;
}
