import type { AlternativePageContent } from "./types";

// AUTO-GENERATED by scripts/generate-batch-video-ad-matrix.ts
// Vertical: HVAC Companies · Angle: video production alternative
export const hvacCompaniesVideoProductionAlternative: AlternativePageContent = {
  slug: "hvac-companies-video-production-alternative",
  type: "direct-competitor",
  competitor: {
    name: "Traditional HVAC Companies Video Production",
    shortName: "HVAC Video Production",
    pricing: "$200-$600per video (Home Services UGC Creators)",
    description:
      "The legacy way residential HVAC companies running $2M-$25M/year with 5-50 trucks buy video creative — typically a home services ugc creators engagement that ships 1-8 videos per cycle at high per-unit cost.",
  },
  meta: {
    title: "HVAC Companies Video Production Alternative — Batch Creative That Ships in 24 Hours",
    description:
      "Traditional hvac video production ships 4 ads a quarter. Batch ships 300-1,000 in 24 hours from one 20-min recording. Same real face. ≈$5/ad. From $1,497 flat.",
    keywords: [
      "hvac-companies video production alternative",
      "video production for hvac-companies",
      "hvac ad production alternative",
      "alternative to hvac video agency",
      "batch video production for hvac-companies",
      "hvac creative production alternative",
      "fastest video production for hvac-companies",
    ],
  },
  hero: {
    badge: "HVAC Video Production Alternative",
    headline: "HVAC Video Production",
    headlineAccent: "Reinvented as a 24-Hour Batch.",
    subheadline:
      "Traditional hvac video production was built for the brand-film era — 1-2 polished hero videos per quarter. Paid social in 2026 needs creative volume the old model cannot supply. Prestyj is the alternative: HVAC-researched scripts, your real face, 300-1,000 vertical ads delivered in 24 hours, flat fee from $1,497. Built for the rotation cadence Meta and TikTok actually require.",
  },
  industryStats: [
    {
      stat: "300-1,000",
      description: "ad variations per hvac batch — versus 1-8 from a typical production engagement",
    },
    {
      stat: "≈$5",
      description:
        "cost per ad at the 500-ad tier — versus $200-$600per video for home services ugc creators",
    },
    {
      stat: "24 hrs",
      description:
        "turnaround from footage delivery — versus 14-45 days through traditional production",
    },
    {
      stat: "0",
      description: "monthly retainer or subscription — flat one-time fee per batch",
    },
  ],
  comparison: {
    features: [
      {
        feature: "Vertical-researched scripts (HVAC-specific)",
        prestyj: true,
        competitor: false,
        note: "Most home services ugc creators engagements ship video production, not vertical research",
      },
      {
        feature: "Variations per delivery",
        prestyj: "300-1,000",
        competitor: "1-8",
      },
      {
        feature: "Turnaround SLA",
        prestyj: "24 hrs from footage",
        competitor: "14-45 days",
      },
      {
        feature: "Pricing model",
        prestyj: "Flat one-time per batch",
        competitor: "Per video / per gig",
      },
      {
        feature: "Built for ad fatigue / refresh cadence",
        prestyj: true,
        competitor: false,
      },
      {
        feature: "Uses your real face — not AI or hired actor",
        prestyj: true,
        competitor: "false" as unknown as boolean | string,
        note: "UGC creators are hired models — not the actual ${v.shortName.toLowerCase()}",
      },
      {
        feature: "Cost per fully tested angle",
        prestyj: "≈$500",
        competitor: "$3K-$15K per tested angle",
      },
      {
        feature: "Error revisions included",
        prestyj: true,
        competitor: "Varies",
      },
    ],
    competitorPricing: {
      price: "$200-$600",
      period: "per video",
      note: "Home Services UGC Creators is the dominant hvac video production model. Pricing covers 1-8 polished videos per cycle; cannot supply the 50+ creatives/ad-set Meta requires for learning-phase exit.",
      pros: [
        "Higher production polish per individual video",
        "Single-creative deliverables suitable for hero/brand work",
        "Direct creative control over each video",
      ],
      cons: [
        "Cannot ship at the volume paid social actually requires",
        "Per-angle math is brutal — $3K-$15K per fully tested angle",
        "Turnaround timelines incompatible with event-driven creative",
        "Heat-wave Tuesday means peak demand on Wednesday — but your ads were last refreshed in March",
        "the hidden cost of static creative for HVAC is missed weather windows — every heat event is a 7-day demand spike and your competition's ads are already running",
      ],
    },
    prestyjPricing: {
      price: "$1,997",
      period: "/mo",
      note: "$1,997/mo Starter · $3,997 setup · ad budget + AI agents included",
      pros: [
        "300-1,000 ad variations per batch",
        "HVAC-researched scripts written for you",
        "Your real face, your real footage — no AI, no hired actors",
        "24-hour turnaround from footage delivery",
        "Flat fee, no retainer, no subscription",
        "Designed for hvac CPL profile ($22-$55 per booked appointment)",
      ],
      cons: [],
    },
  },
  whySwitch: [
    {
      icon: "Zap",
      title: "HVAC need creative volume the old model cannot supply",
      description:
        "Heat-wave Tuesday means peak demand on Wednesday — but your ads were last refreshed in March The old production model was architected for hero videos, not the 50+ fresh creatives per ad set that Meta and TikTok require to exit learning. Batch is purpose-built for the new cadence.",
    },
    {
      icon: "DollarSign",
      title: "Per-angle math finally works",
      description:
        "The hidden cost of static creative for HVAC is missed weather windows — every heat event is a 7-day demand spike and your competition's ads are already running. Cost per fully tested angle for hvac drops from $3K-$15K (traditional) to roughly $500 (batch). On unit economics of $280 service call → $7,500-$22,000 system replacement, that delta funds an entire additional creative experiment per quarter.",
    },
    {
      icon: "Clock",
      title: "Event-driven creative becomes possible",
      description:
        "ServiceTitan tells you which job pays — it doesn't tell you which ad creative drove it Batch delivers in 24 hours, which means hvac can finally ship event-specific creative inside the window when it matters — instead of 14 days after the event when the demand spike has already collapsed.",
    },
    {
      icon: "Target",
      title: "Vertical research is built in",
      description:
        "Generic 'video production' ships generic creative. Batch begins with a vertical research pass on the highest-converting hvac hook patterns from current-quarter ad libraries — meaning the scripts are already tuned to hvac pain before you hit record.",
    },
  ],
  whenCompetitorFits: [
    "You need a single high-polish brand film for a website hero or an investor deck",
    "You're producing a long-form documentary or case-study video where a 24-hour batch cadence is irrelevant",
    "You have a creative team that can absorb production internally and you only need 1-2 polished assets per quarter",
  ],
  whenPrestyjFits: [
    "You're residential HVAC companies running $2M-$25M/year with 5-50 trucks actively running paid social and CPL is rising due to creative fatigue",
    "You ship fewer than 50 fresh creatives per ad set per month and your accounts live in the learning phase",
    "You need event-driven or seasonal creative inside 24-72 hour windows",
    "You want hvac-researched scripts written for you — not generic 'video production'",
    "You want flat-fee pricing with cost-per-tested-angle math that actually pencils out (≈$500/angle)",
  ],
  relatedResources: [
    {
      href: "/batch-video-ads",
      title: "Batch Video Ads — the Service",
      description:
        "How Prestyj turns 20 minutes of footage into 300-1,000 vertical ads in 24 hours.",
    },
    {
      href: "/best-for/batch-video-ads-for-hvac-companies",
      title: "Batch Video Ads for HVAC Companies",
      description: "Use case page covering hvac-specific pain points and pricing math.",
    },
    {
      href: "/best-for/cost-per-tested-ad-angle-for-hvac-companies",
      title: "Cost Per Tested Ad Angle for HVAC",
      description:
        "Full pricing breakdown across batch, agency, freelancer, and in-house production paths.",
    },
    {
      href: "/compare/prestyj-vs-ugc-creator-video-for-hvac-companies",
      title: "Prestyj vs Home Services UGC Creators (for HVAC)",
      description: "Head-to-head comparison against the dominant hvac alternative.",
    },
  ],
  cta: {
    headline: "HVAC Video Production, Re-Engineered for Paid Social.",
    subheadline:
      "Send us 20 minutes of footage and we'll deliver a complete batch of hvac-specific video ads organized by angle — ready to test on Meta and TikTok within days.",
    buttonText: "Book a Demo",
    buttonHref: "/book-demo",
    footnote: "Packages from $1,497 · 24-hour delivery · No retainer",
  },
};
