import type { AlternativePageContent } from "./types";

// AUTO-GENERATED by scripts/generate-batch-video-ad-matrix.ts
// Vertical: Media Buyers · Angle: video production alternative
export const mediaBuyersVideoProductionAlternative: AlternativePageContent = {
  slug: "media-buyers-video-production-alternative",
  type: "direct-competitor",
  competitor: {
    name: "Traditional Media Buyers Video Production",
    shortName: "Media Buyers Video Production",
    pricing: "$25-$500per gig (Fiverr Video Editors)",
    description:
      "The legacy way in-house media buyers and performance marketers managing $50K-$2M/month in paid social spend buy video creative — typically a fiverr video editors engagement that ships 1-8 videos per cycle at high per-unit cost.",
  },
  meta: {
    title: "Media Buyers Video Production Alternative — Batch Creative That Ships in 24 Hours | PRESTYJ",
    description:
      "Traditional media buyers video production ships 4 ads a quarter. Batch ships 300-1,000 in 24 hours from one 20-min recording. Same real face. ≈$5/ad. From $1,497 flat.",
    keywords: [
      "media-buyers video production alternative",
      "video production for media-buyers",
      "media buyers ad production alternative",
      "alternative to media buyers video agency",
      "batch video production for media-buyers",
      "media buyers creative production alternative",
      "fastest video production for media-buyers",
    ],
  },
  hero: {
    badge: "Media Buyers Video Production Alternative",
    headline: "Media Buyers Video Production",
    headlineAccent: "Reinvented as a 24-Hour Batch.",
    subheadline:
      "Traditional media buyers video production was built for the brand-film era — 1-2 polished hero videos per quarter. Paid social in 2026 needs creative volume the old model cannot supply. Prestyj is the alternative: Media Buyers-researched scripts, your real face, 300-1,000 vertical ads delivered in 24 hours, flat fee from $1,497. Built for the rotation cadence Meta and TikTok actually require.",
  },
  industryStats: [
    {
      stat: "300-1,000",
      description: "ad variations per media buyers batch — versus 1-8 from a typical production engagement",
    },
    {
      stat: "≈$5",
      description: "cost per ad at the 500-ad tier — versus $25-$500per gig for fiverr video editors",
    },
    {
      stat: "24 hrs",
      description: "turnaround from footage delivery — versus 14-45 days through traditional production",
    },
    {
      stat: "0",
      description: "monthly retainer or subscription — flat one-time fee per batch",
    },
  ],
  comparison: {
    features: [
      {
        feature: "Vertical-researched scripts (Media Buyers-specific)",
        prestyj: true,
        competitor: false,
        note: "Most fiverr video editors engagements ship video production, not vertical research",
      },
      {
        feature: "Variations per delivery",
        prestyj: "300-1,000",
        competitor: "1-8",
      },
      {
        feature: "Turnaround SLA",
        prestyj: "24 hrs from footage",
        competitor: "14-45 days",
      },
      {
        feature: "Pricing model",
        prestyj: "Flat one-time per batch",
        competitor: "Per video / per gig",
      },
      {
        feature: "Built for ad fatigue / refresh cadence",
        prestyj: true,
        competitor: false,
      },
      {
        feature: "Uses your real face — not AI or hired actor",
        prestyj: true,
        competitor: "true" as unknown as boolean | string,
        note: "Both use your real face, but only batch ships at scale",
      },
      {
        feature: "Cost per fully tested angle",
        prestyj: "≈$500",
        competitor: "$3K-$15K per tested angle",
      },
      {
        feature: "Error revisions included",
        prestyj: true,
        competitor: "Varies",
      },
    ],
    competitorPricing: {
      price: "$25-$500",
      period: "per gig",
      note: "Fiverr Video Editors is the dominant media buyers video production model. Pricing covers 1-8 polished videos per cycle; cannot supply the 50+ creatives/ad-set Meta requires for learning-phase exit.",
      pros: [
        "Higher production polish per individual video",
        "Single-creative deliverables suitable for hero/brand work",
        "Direct creative control over each video",
      ],
      cons: [
        "Cannot ship at the volume paid social actually requires",
        "Per-angle math is brutal — $3K-$15K per fully tested angle",
        "Turnaround timelines incompatible with event-driven creative",
        "You can ship 50 ad sets a week — but your creative team can ship 4 videos",
        "the hidden cost is the 'creative bottleneck tax' — your buying skill is capped by how many videos you have to test",
      ],
    },
    prestyjPricing: {
      price: "$1,497 – $3,997",
      note: "Flat fee. 300 ads / 3 angles at $1,497. 500 ads / 5 angles at $2,497. 1,000 ads / 10 angles at $3,997.",
      pros: [
        "300-1,000 ad variations per batch",
        "Media Buyers-researched scripts written for you",
        "Your real face, your real footage — no AI, no hired actors",
        "24-hour turnaround from footage delivery",
        "Flat fee, no retainer, no subscription",
        "Designed for media buyers CPL profile (30-60% lower vs static rotation)",
      ],
      cons: [],
    },
  },
  whySwitch: [
    {
      icon: "Zap",
      title: "Media Buyers need creative volume the old model cannot supply",
      description:
        "You can ship 50 ad sets a week — but your creative team can ship 4 videos The old production model was architected for hero videos, not the 50+ fresh creatives per ad set that Meta and TikTok require to exit learning. Batch is purpose-built for the new cadence.",
    },
    {
      icon: "DollarSign",
      title: "Per-angle math finally works",
      description:
        "The hidden cost is the 'creative bottleneck tax' — your buying skill is capped by how many videos you have to test. Cost per fully tested angle for media buyers drops from $3K-$15K (traditional) to roughly $500 (batch). On unit economics of every 1-point CPA improvement on a $200K/month account = $20K-$60K saved/quarter, that delta funds an entire additional creative experiment per quarter.",
    },
    {
      icon: "Clock",
      title: "Event-driven creative becomes possible",
      description:
        "The algorithm exits learning at 50 fresh creatives per ad set, and you have 6 Batch delivers in 24 hours, which means media buyers can finally ship event-specific creative inside the window when it matters — instead of 14 days after the event when the demand spike has already collapsed.",
    },
    {
      icon: "Target",
      title: "Vertical research is built in",
      description:
        "Generic 'video production' ships generic creative. Batch begins with a vertical research pass on the highest-converting media buyers hook patterns from current-quarter ad libraries — meaning the scripts are already tuned to media buyers pain before you hit record.",
    },
  ],
  whenCompetitorFits: [
    "You need a single high-polish brand film for a website hero or an investor deck",
    "You're producing a long-form documentary or case-study video where a 24-hour batch cadence is irrelevant",
    "You have a creative team that can absorb production internally and you only need 1-2 polished assets per quarter",
  ],
  whenPrestyjFits: [
    "You're in-house media buyers and performance marketers managing $50K-$2M/month in paid social spend actively running paid social and CPL is rising due to creative fatigue",
    "You ship fewer than 50 fresh creatives per ad set per month and your accounts live in the learning phase",
    "You need event-driven or seasonal creative inside 24-72 hour windows",
    "You want media buyers-researched scripts written for you — not generic 'video production'",
    "You want flat-fee pricing with cost-per-tested-angle math that actually pencils out (≈$500/angle)",
  ],
  relatedResources: [
    {
      href: "/batch-video-ads",
      title: "Batch Video Ads — the Service",
      description: "How Prestyj turns 20 minutes of footage into 300-1,000 vertical ads in 24 hours.",
    },
    {
      href: "/best-for/batch-video-ads-for-media-buyers",
      title: "Batch Video Ads for Media Buyers",
      description: "Use case page covering media buyers-specific pain points and pricing math.",
    },
    {
      href: "/best-for/cost-per-tested-ad-angle-for-media-buyers",
      title: "Cost Per Tested Ad Angle for Media Buyers",
      description: "Full pricing breakdown across batch, agency, freelancer, and in-house production paths.",
    },
    {
      href: "/compare/prestyj-vs-fiverr-video-for-media-buyers",
      title: "Prestyj vs Fiverr Video Editors (for Media Buyers)",
      description: "Head-to-head comparison against the dominant media buyers alternative.",
    },
  ],
  cta: {
    headline: "Media Buyers Video Production, Re-Engineered for Paid Social.",
    subheadline:
      "Send us 20 minutes of footage and we'll deliver a complete batch of media buyers-specific video ads organized by angle — ready to test on Meta and TikTok within days.",
    buttonText: "Book a Demo",
    buttonHref: "/book-demo",
    footnote: "Packages from $1,497 · 24-hour delivery · No retainer",
  },
};
