import type { AlternativePageContent } from "./types";

// AUTO-GENERATED by scripts/generate-batch-video-ad-matrix.ts
// Vertical: Real Estate Teams · Angle: video production alternative
export const realEstateTeamsVideoProductionAlternative: AlternativePageContent = {
  slug: "real-estate-teams-video-production-alternative",
  type: "direct-competitor",
  competitor: {
    name: "Traditional Real Estate Teams Video Production",
    shortName: "RE Teams Video Production",
    pricing: "$110-$220/month (AI Avatar Tools)",
    description:
      "The legacy way real estate teams of 5-50 agents running paid social as a primary buyer/seller acquisition channel buy video creative — typically a ai avatar tools engagement that ships 1-8 videos per cycle at high per-unit cost.",
  },
  meta: {
    title: "Real Estate Teams Video Production Alternative — Batch Creative That Ships in 24 Hours",
    description:
      "Traditional re teams video production ships 4 ads a quarter. Batch ships 300-1,000 in 24 hours from one 20-min recording. Same real face. ≈$5/ad. From $1,497 flat.",
    keywords: [
      "real-estate-teams video production alternative",
      "video production for real-estate-teams",
      "re teams ad production alternative",
      "alternative to re teams video agency",
      "batch video production for real-estate-teams",
      "re teams creative production alternative",
      "fastest video production for real-estate-teams",
    ],
  },
  hero: {
    badge: "RE Teams Video Production Alternative",
    headline: "RE Teams Video Production",
    headlineAccent: "Reinvented as a 24-Hour Batch.",
    subheadline:
      "Traditional re teams video production was built for the brand-film era — 1-2 polished hero videos per quarter. Paid social in 2026 needs creative volume the old model cannot supply. Prestyj is the alternative: RE Teams-researched scripts, your real face, 300-1,000 vertical ads delivered in 24 hours, flat fee from $1,497. Built for the rotation cadence Meta and TikTok actually require.",
  },
  industryStats: [
    {
      stat: "300-1,000",
      description:
        "ad variations per re teams batch — versus 1-8 from a typical production engagement",
    },
    {
      stat: "≈$5",
      description: "cost per ad at the 500-ad tier — versus $110-$220/month for ai avatar tools",
    },
    {
      stat: "24 hrs",
      description:
        "turnaround from footage delivery — versus 14-45 days through traditional production",
    },
    {
      stat: "0",
      description: "monthly retainer or subscription — flat one-time fee per batch",
    },
  ],
  comparison: {
    features: [
      {
        feature: "Vertical-researched scripts (RE Teams-specific)",
        prestyj: true,
        competitor: false,
        note: "Most ai avatar tools engagements ship video production, not vertical research",
      },
      {
        feature: "Variations per delivery",
        prestyj: "300-1,000",
        competitor: "1-8",
      },
      {
        feature: "Turnaround SLA",
        prestyj: "24 hrs from footage",
        competitor: "14-45 days",
      },
      {
        feature: "Pricing model",
        prestyj: "Flat one-time per batch",
        competitor: "Recurring monthly",
      },
      {
        feature: "Built for ad fatigue / refresh cadence",
        prestyj: true,
        competitor: false,
      },
      {
        feature: "Uses your real face — not AI or hired actor",
        prestyj: true,
        competitor: "false" as unknown as boolean | string,
        note: "AI avatars don't look like you — buyers can clock them",
      },
      {
        feature: "Cost per fully tested angle",
        prestyj: "≈$500",
        competitor: "$3K-$15K per tested angle",
      },
      {
        feature: "Error revisions included",
        prestyj: true,
        competitor: "Varies",
      },
    ],
    competitorPricing: {
      price: "$110-$220",
      period: "/month",
      note: "AI Avatar Tools is the dominant re teams video production model. Pricing covers 1-8 polished videos per cycle; cannot supply the 50+ creatives/ad-set Meta requires for learning-phase exit.",
      pros: [
        "Higher production polish per individual video",
        "Single-creative deliverables suitable for hero/brand work",
        "Direct creative control over each video",
      ],
      cons: [
        "Cannot ship at the volume paid social actually requires",
        "Per-angle math is brutal — $3K-$15K per fully tested angle",
        "Turnaround timelines incompatible with event-driven creative",
        "Buyer leads and seller leads need different creative — most teams run only buyer ads",
        "the hidden cost of portal leads is permanent buyer-side bias and zero brand equity — every dollar to Zillow strengthens Zillow, not your team brand",
      ],
    },
    prestyjPricing: {
      price: "$1,997",
      period: "/mo",
      note: "$1,997/mo Starter · $3,997 setup · ad budget + AI agents included",
      pros: [
        "300-1,000 ad variations per batch",
        "RE Teams-researched scripts written for you",
        "Your real face, your real footage — no AI, no hired actors",
        "24-hour turnaround from footage delivery",
        "Flat fee, no retainer, no subscription",
        "Designed for re teams CPL profile ($12-$38 per qualified buyer/seller lead)",
      ],
      cons: [],
    },
  },
  whySwitch: [
    {
      icon: "Zap",
      title: "RE Teams need creative volume the old model cannot supply",
      description:
        "Buyer leads and seller leads need different creative — most teams run only buyer ads The old production model was architected for hero videos, not the 50+ fresh creatives per ad set that Meta and TikTok require to exit learning. Batch is purpose-built for the new cadence.",
    },
    {
      icon: "DollarSign",
      title: "Per-angle math finally works",
      description:
        "The hidden cost of portal leads is permanent buyer-side bias and zero brand equity — every dollar to Zillow strengthens Zillow, not your team brand. Cost per fully tested angle for re teams drops from $3K-$15K (traditional) to roughly $500 (batch). On unit economics of $8,000-$24,000 GCI per closed transaction, that delta funds an entire additional creative experiment per quarter.",
    },
    {
      icon: "Clock",
      title: "Event-driven creative becomes possible",
      description:
        "Listing video ads, market-update ads, and seller-pain-point ads are three full creative tracks and your team has none Batch delivers in 24 hours, which means re teams can finally ship event-specific creative inside the window when it matters — instead of 14 days after the event when the demand spike has already collapsed.",
    },
    {
      icon: "Target",
      title: "Vertical research is built in",
      description:
        "Generic 'video production' ships generic creative. Batch begins with a vertical research pass on the highest-converting re teams hook patterns from current-quarter ad libraries — meaning the scripts are already tuned to re teams pain before you hit record.",
    },
  ],
  whenCompetitorFits: [
    "You need a single high-polish brand film for a website hero or an investor deck",
    "You're producing a long-form documentary or case-study video where a 24-hour batch cadence is irrelevant",
    "You have a creative team that can absorb production internally and you only need 1-2 polished assets per quarter",
  ],
  whenPrestyjFits: [
    "You're real estate teams of 5-50 agents running paid social as a primary buyer/seller acquisition channel actively running paid social and CPL is rising due to creative fatigue",
    "You ship fewer than 50 fresh creatives per ad set per month and your accounts live in the learning phase",
    "You need event-driven or seasonal creative inside 24-72 hour windows",
    "You want re teams-researched scripts written for you — not generic 'video production'",
    "You want flat-fee pricing with cost-per-tested-angle math that actually pencils out (≈$500/angle)",
  ],
  relatedResources: [
    {
      href: "/batch-video-ads",
      title: "Batch Video Ads — the Service",
      description:
        "How Prestyj turns 20 minutes of footage into 300-1,000 vertical ads in 24 hours.",
    },
    {
      href: "/best-for/batch-video-ads-for-real-estate-teams",
      title: "Batch Video Ads for Real Estate Teams",
      description: "Use case page covering re teams-specific pain points and pricing math.",
    },
    {
      href: "/best-for/cost-per-tested-ad-angle-for-real-estate-teams",
      title: "Cost Per Tested Ad Angle for RE Teams",
      description:
        "Full pricing breakdown across batch, agency, freelancer, and in-house production paths.",
    },
    {
      href: "/compare/prestyj-vs-ai-avatar-tool-video-for-real-estate-teams",
      title: "Prestyj vs AI Avatar Tools (for RE Teams)",
      description: "Head-to-head comparison against the dominant re teams alternative.",
    },
  ],
  cta: {
    headline: "RE Teams Video Production, Re-Engineered for Paid Social.",
    subheadline:
      "Send us 20 minutes of footage and we'll deliver a complete batch of re teams-specific video ads organized by angle — ready to test on Meta and TikTok within days.",
    buttonText: "Book a Demo",
    buttonHref: "/book-demo",
    footnote: "Packages from $1,497 · 24-hour delivery · No retainer",
  },
};
