import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { getPhaseOneBatchVideoAdsVerticals } from "../src/lib/batch-video-ads/verticals";
import type { BatchVideoAdsVerticalDefinition } from "../src/lib/batch-video-ads/verticals";

const ROOT = process.cwd();
const BEST_FOR_DIR = join(ROOT, "src/lib/best-for");
const BEST_FOR_INDEX = join(BEST_FOR_DIR, "index.ts");
const GENERATOR_LABEL = "scripts/generate-batch-video-ad-organic-matrix.ts";

type PageAngle = "batch-video-ads" | "creative-testing";

interface GeneratedPage {
  slug: string;
  variableName: string;
  content: string;
  angle: PageAngle;
}

function toTitleCase(value: string): string {
  return value
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

function toPascalCase(value: string): string {
  return value
    .split(/[-\s]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function escapeString(value: string): string {
  return JSON.stringify(value);
}

function list(items: readonly string[]): string {
  return items.map((item) => `      ${escapeString(item)},`).join("\n");
}

function lowerFirst(value: string): string {
  return value.charAt(0).toLowerCase() + value.slice(1);
}

function asAdjective(value: string): string {
  const lower = value.toLowerCase();

  if (lower.endsWith("s")) {
    return lower.slice(0, -1);
  }

  return lower;
}

function withArticle(value: string): string {
  if (value.toLowerCase().startsWith("ecommerce")) {
    return `an ${value}`;
  }

  const article = /^[aeiou]/i.test(value) ? "an" : "a";
  return `${article} ${value}`;
}

function createKeywords(vertical: BatchVideoAdsVerticalDefinition, angle: PageAngle): string[] {
  if (angle === "creative-testing") {
    return [
      `creative testing for ${vertical.shortName.toLowerCase()}`,
      `ad creative testing for ${vertical.slug}`,
      `${vertical.shortName.toLowerCase()} facebook ad creative testing`,
      `${vertical.shortName.toLowerCase()} paid social creative testing`,
      `${vertical.shortName.toLowerCase()} ad fatigue solution`,
      `video ad testing for ${vertical.slug}`,
    ];
  }

  return [
    `batch video ads for ${vertical.shortName.toLowerCase()}`,
    `video ads for ${vertical.slug}`,
    `${vertical.shortName.toLowerCase()} video ad production`,
    `${vertical.shortName.toLowerCase()} facebook ads creative`,
    `${vertical.shortName.toLowerCase()} ad creative volume`,
    `100 video ads for ${vertical.slug}`,
  ];
}

function createBatchPage(vertical: BatchVideoAdsVerticalDefinition): GeneratedPage {
  const slug = `batch-video-ads-for-${vertical.slug}`;
  const variableName = `batchVideoAdsFor${toPascalCase(vertical.slug)}`;
  const firstTrigger = vertical.seasonalTriggers[0] ?? "seasonal demand";
  const firstAngle = vertical.adAngleExamples[0] ?? "The specific buyer problem hook";
  const secondAngle = vertical.adAngleExamples[1] ?? "The hidden cost hook";
  const thirdAngle = vertical.adAngleExamples[2] ?? "The urgency hook";
  const fourthAngle = vertical.adAngleExamples[3] ?? "The trust proof hook";
  const verticalLower = vertical.shortName.toLowerCase();
  const verticalAdjective = asAdjective(vertical.shortName);
  const statusQuoLabel = toTitleCase(vertical.statusQuoCompetitor);

  const content = `import type { BestForPageContent } from "./types";

// AUTO-GENERATED by ${GENERATOR_LABEL}
// Vertical: ${vertical.nicheName} · Angle: batch video ads
export const ${variableName}: BestForPageContent = {
  slug: ${escapeString(slug)},
  niche: {
    name: ${escapeString(`Batch Video Ads for ${vertical.nicheName}`)},
    shortName: ${escapeString(vertical.shortName)},
    description: ${escapeString(`${vertical.audience} that need enough vertical ad variations to test paid social angles without waiting weeks for production.`)},
  },
  meta: {
    title: ${escapeString(`Batch Video Ads for ${vertical.nicheName} | 100-1,000 Ads`)},
    description: ${escapeString(`Batch video ads for ${verticalLower}: turn one recording into 100, 300, 500, or 1,000 vertical ad variations built around ${lowerFirst(vertical.painPoints[0])}`)},
    keywords: [
${list(createKeywords(vertical, "batch-video-ads"))}
    ],
  },
  hero: {
    badge: ${escapeString(`Batch Video Ads for ${vertical.shortName}`)},
    headline: ${escapeString(`${vertical.nicheName} Need More Than One Generic Video Ad.`)},
    headlineAccent: ${escapeString("Batch gives you the creative volume to find what buyers respond to.")},
    subheadline: ${escapeString(`Prestyj turns one founder or operator recording into 100-1,000 scripted vertical ad variations for ${verticalLower}. Test pain points, seasonal triggers like ${firstTrigger}, and high-intent offers without hiring another editor, agency, or creator.`)},
  },
  whyBestFor: [
    {
      icon: "Target",
      title: ${escapeString(vertical.painPoints[0])},
      description: ${escapeString(`${vertical.shortName} campaigns underperform when every buyer sees the same generic message. Batch creative splits the market into specific angles — ${firstAngle}, ${secondAngle}, and other hooks that let the account learn which problem actually creates demand.`)},
    },
    {
      icon: "DollarSign",
      title: ${escapeString(`The economics support testing: ${vertical.economics.customerValue}`)},
      description: ${escapeString(`${vertical.economics.costPressure} ${vertical.economics.batchLeverage} When one booked opportunity can justify the whole production sprint, starving the account with three ads is the expensive option.`)},
    },
    {
      icon: "Clock",
      title: ${escapeString(`${toTitleCase(firstTrigger)} windows move faster than traditional production.`)},
      description: ${escapeString(`The best ${verticalLower} angles are often tied to timing: ${vertical.seasonalTriggers.join(", ")}. Batch production gives your team ready-to-test creative while the trigger is still active instead of after the opportunity has passed.`)},
    },
    {
      icon: "Shield",
      title: ${escapeString(`Compliance-aware scripts keep volume from becoming reckless.`)},
      description: ${escapeString(vertical.complianceNotes)},
    },
    {
      icon: "Sparkles",
      title: ${escapeString(`Your real operator beats ${vertical.statusQuoCompetitor}.`)},
      description: ${escapeString(`The status quo for ${verticalLower} is ${vertical.statusQuoCompetitor}. Prestyj uses your real face, your real offer, and a structured script matrix so the account gets authenticity and volume at the same time.`)},
    },
  ],
  painPoints: [
    {
      problem: ${escapeString(vertical.painPoints[0])},
      solution: ${escapeString(`Build a full lane of ads around that problem instead of mentioning it once. Prestyj turns it into hooks, proof points, objections, and CTAs so your media buyer can see whether the market cares.`)},
    },
    {
      problem: ${escapeString(vertical.painPoints[1])},
      solution: ${escapeString(`Use batch production to test separate ad families for each buyer motivation. ${vertical.shortName} can compare urgency, trust, cost, timing, and status quo angles without another shoot.`)},
    },
    {
      problem: ${escapeString(vertical.painPoints[2])},
      solution: ${escapeString(`Give that high-value category its own creative inventory. A 300, 500, or 1,000 ad batch lets your team isolate which offer deserves more spend.`)},
    },
    {
      problem: ${escapeString(`You are relying on ${vertical.statusQuoCompetitor} instead of owned creative learning.`)},
      solution: ${escapeString(`Batch creative gives ${verticalLower} a reusable library that can be launched, paused, refreshed, and expanded without renting every lead from the same crowded channels.`)},
    },
    {
      problem: ${escapeString(`You do not have time to write ${verticalAdjective} ad scripts from scratch.`)},
      solution: ${escapeString(`Prestyj writes the scripts, maps the angles, edits the recording, and delivers finished vertical files. Your team records once and your media buyer gets the creative inputs.`)},
    },
  ],
  comparison: {
    headers: ["Factor", "Prestyj Batch Video Ads", ${escapeString(statusQuoLabel)}],
    rows: [
      {
        feature: "Creative output",
        prestyj: "100, 300, 500, or 1,000 finished ads",
        others: "A handful of generic ads or rented leads",
      },
      {
        feature: "Angle coverage",
        prestyj: ${escapeString(`${firstAngle}, ${secondAngle}, ${thirdAngle}, ${fourthAngle}`)},
        others: "Usually one broad message",
      },
      {
        feature: "Production model",
        prestyj: "One recording session plus a scripted variation matrix",
        others: "New brief, vendor, or campaign for every idea",
      },
      {
        feature: "Economics",
        prestyj: ${escapeString(vertical.economics.batchLeverage)},
        others: ${escapeString(vertical.economics.costPressure)},
      },
      {
        feature: "Primary CTA",
        prestyj: "Send traffic to the winning offer and refresh before fatigue",
        others: "Wait for the next production cycle",
      },
    ],
  },
  faq: [
    {
      question: ${escapeString(`How do batch video ads work for ${verticalLower}?`)},
      answer: ${escapeString(`Prestyj writes ${withArticle(`${verticalAdjective}-specific`)} script matrix, you record the scripts once, and we edit that footage into finished vertical ad variations for Meta, TikTok, YouTube Shorts, and similar placements.`)},
    },
    {
      question: ${escapeString(`What angles should ${verticalLower} test first?`)},
      answer: ${escapeString(`Start with ${vertical.adAngleExamples.join(", ")}. Those angles map to real ${verticalLower} buying triggers instead of generic brand awareness.`)},
    },
    {
      question: ${escapeString(`Is this a replacement for ${vertical.statusQuoCompetitor}?`)},
      answer: ${escapeString(`It replaces the creative production bottleneck, not every marketing function. Your team or agency still manages media buying; Prestyj supplies the high-volume ad creative library.`)},
    },
    {
      question: ${escapeString(`What compliance guardrails matter for ${verticalLower} ads?`)},
      answer: ${escapeString(vertical.complianceNotes)},
    },
    {
      question: ${escapeString(`Which batch size should ${verticalLower} choose?`)},
      answer: ${escapeString(`Choose 100 ads for a focused first test, 300 for three problem lanes, 500 for the recommended matrix, and 1,000 if you need to test many ${verticalLower} triggers or refresh a larger account.`)},
    },
  ],
  cta: {
    headline: ${escapeString(`${vertical.nicheName}: Turn One Recording Into a Paid-Social Test Library.`)},
    subheadline: ${escapeString(`Get scripts and finished video ads built around ${verticalLower} economics, timing triggers, compliance constraints, and buyer objections.`)},
    buttonText: "See Batch Pricing",
    buttonHref: "/batch-video-ads#pricing",
    footnote: ${escapeString(`One-time packs from $497 · ${vertical.calculatorPath === "/batch-video-ad-roi-calculator" ? "ROI calculator available" : "Cost-per-angle calculator available"}`)},
  },
};
`;

  return { slug, variableName, content, angle: "batch-video-ads" };
}

function createCreativeTestingPage(vertical: BatchVideoAdsVerticalDefinition): GeneratedPage {
  const slug = `creative-testing-for-${vertical.slug}`;
  const variableName = `creativeTestingFor${toPascalCase(vertical.slug)}`;
  const [painOne, painTwo, painThree] = vertical.painPoints;
  const verticalLower = vertical.shortName.toLowerCase();
  const verticalAdjective = asAdjective(vertical.shortName);
  const articleVertical = withArticle(verticalAdjective);
  const content = `import type { BestForPageContent } from "./types";

// AUTO-GENERATED by ${GENERATOR_LABEL}
// Vertical: ${vertical.nicheName} · Angle: creative testing
export const ${variableName}: BestForPageContent = {
  slug: ${escapeString(slug)},
  niche: {
    name: ${escapeString(`Creative Testing for ${vertical.nicheName}`)},
    shortName: ${escapeString(vertical.shortName)},
    description: ${escapeString(`a paid-social creative testing plan for ${vertical.audience}.`)},
  },
  meta: {
    title: ${escapeString(`Creative Testing for ${vertical.nicheName} | Paid Social Ad Matrix`)},
    description: ${escapeString(`Creative testing for ${verticalLower} using a structured matrix of hooks, buyer pains, seasonal triggers, and compliance-aware video ad variations.`)},
    keywords: [
${list(createKeywords(vertical, "creative-testing"))}
    ],
  },
  hero: {
    badge: ${escapeString(`Creative Testing for ${vertical.shortName}`)},
    headline: ${escapeString(`${vertical.nicheName} Should Not Test One Ad at a Time.`)},
    headlineAccent: ${escapeString("Test the angle matrix instead.")},
    subheadline: ${escapeString(`A useful ${verticalAdjective} creative test compares buyer problems, timing triggers, offers, objections, and proof. Prestyj supplies the video variation library so your media buyer can find signal without waiting on weekly production.`)},
  },
  whyBestFor: [
    {
      icon: "Target",
      title: "Test buyer problems as separate hypotheses.",
      description: ${escapeString(`For ${verticalLower}, the first hypotheses should include: ${painOne} ${painTwo} ${painThree} Each needs its own lane so the account can show what deserves budget.`)},
    },
    {
      icon: "Zap",
      title: "Test first-three-second hooks, not just finished concepts.",
      description: ${escapeString(`The same offer can win or lose based on the opening. Examples worth testing include ${vertical.adAngleExamples.join(", ")}.`)},
    },
    {
      icon: "Clock",
      title: "Match creative drops to market timing.",
      description: ${escapeString(`${toTitleCase(verticalAdjective)} demand is shaped by ${vertical.seasonalTriggers.join(", ")}. Creative testing works better when those triggers become test lanes before demand peaks.`)},
    },
    {
      icon: "DollarSign",
      title: "Read results through unit economics.",
      description: ${escapeString(`${vertical.economics.customerValue}. That means the best creative test is not the prettiest ad — it is the angle that creates profitable booked opportunities.`)},
    },
    {
      icon: "Shield",
      title: "Keep every test within compliance boundaries.",
      description: ${escapeString(vertical.complianceNotes)},
    },
  ],
  painPoints: [
    {
      problem: "Your creative test is too small to produce reliable signal.",
      solution: "Use a 100-ad batch for one focused problem, 300 ads for three problem lanes, 500 for the recommended matrix, or 1,000 for a full-market sprint.",
    },
    {
      problem: ${escapeString(`Your current ads blur too many ${verticalAdjective} buyer motivations together.`)},
      solution: ${escapeString(`Separate the test into pain, timing, trust, price, and status quo lanes. That keeps ${verticalLower} results readable instead of averaging every buyer into one generic message.`)},
    },
    {
      problem: "Your media buyer cannot scale because the creative library runs out.",
      solution: "Batch production creates enough adjacent variants to refresh winning lanes before the original ad fatigues.",
    },
    {
      problem: ${escapeString(`Your status quo is still ${vertical.statusQuoCompetitor}.`)},
      solution: "Own the learning loop by building a creative library you can test, analyze, and reuse instead of renting attention from the same crowded sources.",
    },
    {
      problem: "Your team does not have a repeatable script matrix.",
      solution: "Prestyj writes the hook, body, objection, proof, and CTA variations, then edits one recording into finished ads.",
    },
  ],
  comparison: {
    headers: ["Testing Layer", "Structured Creative Test", "Thin Creative Test"],
    rows: [
      {
        feature: "Hypotheses",
        prestyj: "Pain, timing, proof, objection, CTA, and status quo lanes",
        others: "One or two broad concepts",
      },
      {
        feature: "Vertical specificity",
        prestyj: ${escapeString(`${vertical.shortName} economics, triggers, and compliance notes built in`)},
        others: "Generic paid-social best practices",
      },
      {
        feature: "Refresh plan",
        prestyj: "Adjacent variants ready when a lane wins",
        others: "Start a new brief after fatigue appears",
      },
      {
        feature: "Cost lens",
        prestyj: ${escapeString(vertical.economics.customerValue)},
        others: "Per-video cost without angle-level learning",
      },
      {
        feature: "Next step",
        prestyj: "Scale the winning problem lane with fresh variants",
        others: "Guess which single ad to remake",
      },
    ],
  },
  faq: [
    {
      question: ${escapeString(`What should a creative test for ${verticalLower} include?`)},
      answer: ${escapeString(`It should include separate hypotheses for buyer pains, timing triggers, proof, objections, offers, and CTAs. For ${verticalLower}, strong starting points include ${vertical.adAngleExamples.join(", ")}.`)},
    },
    {
      question: "How many ads do I need for a creative test?",
      answer: "Use 100 ads for first signal around one problem, 300 for three problem lanes, 500 for the recommended matrix, and 1,000 for a full sprint across many buyer motivations.",
    },
    {
      question: ${escapeString(`How is this different from batch video ads for ${verticalLower}?`)},
      answer: ${escapeString(`This page focuses on the testing methodology. The batch video ads page focuses on the production service and deliverables for ${verticalLower}. Both point to the same pricing because the production system powers the test.`)},
    },
    {
      question: "Does Prestyj analyze the ad account?",
      answer: "No. Prestyj creates the creative library. Your media buyer or agency manages launch structure, budgets, reporting, and optimization.",
    },
    {
      question: ${escapeString(`What compliance issue matters most for ${verticalLower} creative testing?`)},
      answer: ${escapeString(vertical.complianceNotes)},
    },
  ],
  cta: {
    headline: ${escapeString(`Build ${articleVertical} Creative Testing Matrix.`)},
    subheadline: ${escapeString(`Turn one recording into enough ${verticalLower} ads to test buyer problems, timing triggers, objections, proof, and CTAs.`)},
    buttonText: "Pick a Batch Size",
    buttonHref: "/batch-video-ads#pricing",
    footnote: "Creative production only · Media buying not included",
  },
};
`;

  return { slug, variableName, content, angle: "creative-testing" };
}

function ensureBlock(source: string, start: string, end: string, replacementBody: string): string {
  const startToken = `// ${start}`;
  const endToken = `// ${end}`;
  const block = `${startToken}\n${replacementBody}${replacementBody.endsWith("\n") ? "" : "\n"}${endToken}`;

  if (source.includes(startToken) && source.includes(endToken)) {
    const pattern = new RegExp(`${startToken}[\\s\\S]*?${endToken}`);
    return source.replace(pattern, block);
  }

  return source;
}

function patchBestForIndex(pages: GeneratedPage[]): void {
  const source = readFileSync(BEST_FOR_INDEX, "utf8");
  const imports = pages
    .map((page) => `import { ${page.variableName} } from "./${page.slug}";`)
    .join("\n");
  const registrations = pages
    .map((page) => `  "${page.slug}": ${page.variableName},`)
    .join("\n");

  let next = ensureBlock(
    source,
    "BATCH-ORGANIC-MATRIX-IMPORTS-START",
    "BATCH-ORGANIC-MATRIX-IMPORTS-END",
    `${imports}\n`,
  );
  next = ensureBlock(
    next,
    "BATCH-ORGANIC-MATRIX-REGISTER-START",
    "BATCH-ORGANIC-MATRIX-REGISTER-END",
    `${registrations}\n`,
  );

  const hasMarkers =
    source.includes("// BATCH-ORGANIC-MATRIX-IMPORTS-START") &&
    source.includes("// BATCH-ORGANIC-MATRIX-IMPORTS-END") &&
    source.includes("// BATCH-ORGANIC-MATRIX-REGISTER-START") &&
    source.includes("// BATCH-ORGANIC-MATRIX-REGISTER-END");

  if (!hasMarkers) {
    throw new Error(
      "Could not patch src/lib/best-for/index.ts. Add BATCH-ORGANIC-MATRIX marker blocks first.",
    );
  }

  writeFileSync(BEST_FOR_INDEX, next);
}

function main(): void {
  mkdirSync(BEST_FOR_DIR, { recursive: true });
  const pages = getPhaseOneBatchVideoAdsVerticals().flatMap((vertical) => [
    createBatchPage(vertical),
    createCreativeTestingPage(vertical),
  ]);

  for (const page of pages) {
    writeFileSync(join(BEST_FOR_DIR, `${page.slug}.ts`), page.content);
  }

  patchBestForIndex(pages);
  console.log(`Generated ${pages.length} organic batch video ad best-for pages.`);
}

main();
