"use client";

// AUTO-GENERATED by scripts/generate-social-vertical-matrix.ts
import { ComparePageWrapper } from "@/components/sections/compare/ComparePageWrapper";
import { cmosVsInHouseHireForCompareData } from "@/lib/compare/data/prestyj-vs-in-house-hire-for-cmos";

export default function PrestyjVsInHouseHireForCmosPage() {
  return <ComparePageWrapper data={cmosVsInHouseHireForCompareData} />;
}
